<table width="100%" cellspacing="0" cellpadding="0" border="0">
<tbody><tr>
    <td valign="top" align="center" style="padding:20px 0 20px 0;">
        <table width="650" cellspacing="0" cellpadding="10" border="0" bgcolor="#FFFFFF" style="border:1px solid #E0E0E0;">
            
            <tbody><tr>
                <td valign="top"><a target="_blank" href="http://www.applemax.com.br/"><img border="0" style="" alt="AppleMax" src="https://snt147.mail.live.com/Handlers/ImageProxy.mvc?bicild=&amp;canary=COsPz2hGd2hVxpGngDYnaITw84GvI1M7Ts7X5Qj4NwU%3d0&amp;url=http%3a%2f%2fwww.applemax.com.br%2fskin%2fadminhtml%2fbase%2fdefault%2fimages%2flogo_email.gif"></a></td>
            </tr>
            
            <tr>
                <td valign="top">
                    <h1 style="font-size:22px;font-weight:normal;line-height:22px;">Olá, Fabio Ferreira</h1>
                    <p style="font-size:12px;line-height:16px;">
                        Seu pedido foi realizado com sucesso na AppleMax!
                        Assim que o enviarmos, você receberá um novo email com um link para poder rastrear o seu pedido.
                        Poderá verificar o status atual do seu pedido acessando <a target="_blank" style="color:#1E7EC8;" href="http://www.applemax.com.br/customer/account/">sua conta</a>.
                        Se tiver quaisquer dúvidas referente ao seu pedido entre em contato conosco pelo <a style="color:#1E7EC8;" href="mailto:atendimento@applemax.com.br">atendimento@applemax.com.br</a> Seg - Sex, 09hs - 18hs.
                    </p>
                    <p style="font-size:12px;line-height:16px;">Segue abaixo a confirmação do seu pedido. Obrigado novamente por comprar conosco!</p>
            </td></tr>
            <tr>
                <td>
                    <h2 style="font-size:18px;font-weight:normal;">Seu Pedido #100273439 <small>(feito em 24 de janeiro de 2014 18h38min37s BRST)</small></h2>
                </td>
            </tr>
            <tr>
                <td>
                    <table width="650" cellspacing="0" cellpadding="0" border="0">
                        <thead>
                        <tr>
                            <th width="325" bgcolor="#EAEAEA" align="left" style="font-size:13px;padding:5px 9px 6px 9px;line-height:1em;">Informações de Cobrança:</th>
                            <th width="10"></th>
                            <th width="325" bgcolor="#EAEAEA" align="left" style="font-size:13px;padding:5px 9px 6px 9px;line-height:1em;">Forma de Pagamento:</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:7px 9px 9px 9px;border-left:1px solid #EAEAEA;border-bottom:1px solid #EAEAEA;border-right:1px solid #EAEAEA;">
                                Fabio Ferreira<br>

Av do Taboão <br>
2319<br>


SBC,  São Paulo, 09655000<br>
Brasil<br>
T: 11953210896
<br>F: n/a

                            </td>
                            <td>&nbsp;</td>
                            <td valign="top" style="font-size:12px;padding:7px 9px 9px 9px;border-left:1px solid #EAEAEA;border-bottom:1px solid #EAEAEA;border-right:1px solid #EAEAEA;">
                                <p>
    <strong>PagSeguro (Boleto ou Cartão de Crédito)</strong>
        
        	(<a target="_blank" href="http://www.applemax.com.br/pagseguro/pay/redirect/order_id/3505/">pagar</a>)
    
    
</p>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <br>
                    
                    <table width="650" cellspacing="0" cellpadding="0" border="0">
                        <thead>
                        <tr>
                            <th width="325" bgcolor="#EAEAEA" align="left" style="font-size:13px;padding:5px 9px 6px 9px;line-height:1em;">Informações de Envio:</th>
                            <th width="10"></th>
                            <th width="325" bgcolor="#EAEAEA" align="left" style="font-size:13px;padding:5px 9px 6px 9px;line-height:1em;">Forma de Envio:</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:7px 9px 9px 9px;border-left:1px solid #EAEAEA;border-bottom:1px solid #EAEAEA;border-right:1px solid #EAEAEA;">
                                Fabio Ferreira<br>

Av do Taboão <br>
2319<br>


SBC,  São Paulo, 09655000<br>
Brasil<br>
T: 11953210896
<br>F: n/a

                                &nbsp;
                            </td>
                            <td>&nbsp;</td>
                            <td valign="top" style="font-size:12px;padding:7px 9px 9px 9px;border-left:1px solid #EAEAEA;border-bottom:1px solid #EAEAEA;border-right:1px solid #EAEAEA;">
                                Correios - PAC - Em média 11 dia(s)
                                &nbsp;
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <br>
                    
                    <table width="650" cellspacing="0" cellpadding="0" border="0" style="border:1px solid #EAEAEA;">
    <thead>
        <tr>
            <th bgcolor="#EAEAEA" align="left" style="font-size:13px;padding:3px 9px;">Item</th>
            <th bgcolor="#EAEAEA" align="left" style="font-size:13px;padding:3px 9px;">Sku</th>
            <th bgcolor="#EAEAEA" align="center" style="font-size:13px;padding:3px 9px;">Qtd</th>
            <th bgcolor="#EAEAEA" align="right" style="font-size:13px;padding:3px 9px;">Subtotal</th>
        </tr>
    </thead>

            <tbody>
        <tr>
    <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted #CCCCCC;">
        <strong style="font-size:11px;">Capa para iPad Mini - Silicone Transparente</strong>
                                                        </td>
    <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted #CCCCCC;">IPM-1008tr</td>
    <td valign="top" align="center" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted #CCCCCC;">1</td>
    <td valign="top" align="right" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted #CCCCCC;">
                                                <span class="ecxprice">R$29,90</span>            

                    

            </td>
</tr>
    </tbody>
    
    <tbody>
                <tr class="ecxsubtotal">
        <td align="right" style="padding:3px 9px;" colspan="3">
                        Subtotal                    </td>
        <td align="right" style="padding:3px 9px;">
                        <span class="ecxprice">R$29,90</span>                    </td>
    </tr>
            <tr class="ecxshipping">
        <td align="right" style="padding:3px 9px;" colspan="3">
                        Frete                    </td>
        <td align="right" style="padding:3px 9px;">
                        <span class="ecxprice">R$13,30</span>                    </td>
    </tr>
            <tr class="ecxgrand_total">
        <td align="right" style="padding:3px 9px;" colspan="3">
                        <strong>Total Geral</strong>
                    </td>
        <td align="right" style="padding:3px 9px;">
                        <strong><span class="ecxprice">R$43,20</span></strong>
                    </td>
    </tr>
        </tbody>
</table>

                    <p style="font-size:12px;"></p>
                </td>
            </tr>
            <tr>
                <td bgcolor="#EAEAEA" align="center" style="background:#EAEAEA;text-align:center;"><center><p style="font-size:12px;">Atenciosamente, <strong>AppleMax</strong></p></center></td>
            </tr>
        </tbody></table>
    </td>
</tr>
</tbody></table>