        <div class="row-fluid">

    		<form id="fileupload" method="POST" enctype="multipart/form-data">
                <div class="row fileupload-buttonbar">
                    <div class="col-lg-7">
                        <!-- The fileinput-button span is used to style the file input field as button -->
                        <span class="btn btn-success fileinput-button">
                            <i class="glyphicon glyphicon-plus"></i>
                            <span>Escolher Imagem</span>
                            <input type="file" name="files[]" multiple>
                        </span>
                        <button type="submit" class="btn btn-primary start" name="upload-all">
                            <i class="glyphicon glyphicon-upload"></i>
                            <span>Salvar Imagens</span>
                        </button>
                        <button type="reset" class="btn btn-warning cancel">
                            <i class="glyphicon glyphicon-ban-circle"></i>
                            <span>Cancelar Upload</span>
                        </button>
                        <button type="button" class="btn btn-danger delete" style="display:none">
                          <!--  <i class="glyphicon glyphicon-trash"></i>
                            <span>Excluir Selecionadas</span>-->
                        </button>
                     <!--   <input type="checkbox" class="toggle"> -->
                        <!-- The loading indicator is shown during file processing -->
                        <span class="fileupload-loading"></span>
                    </div>
                    <!-- The global progress information -->
                    <div class="col-lg-5 fileupload-progress fade">
                        <!-- The global progress bar -->
                        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                        </div>
                        <!-- The extended global progress information -->
                        <div class="progress-extended">&nbsp;</div>
                    </div>
                </div>
                <!-- The table listing the files available for upload/download -->
                <table role="presentation" class="table table-striped">
                <thead>
                	<tr>
                		<th>Preview</th>                		
                		<th>Nome Arquivo</th>
                		<th>Tamanho</th>
                		<th>Ordem</th>
                		<th>Ações</th>
                	</tr>
                </thead>
                    <tbody class="files">                        
                    </tbody>
                </table>
            </form>
            
                     
            <script id="template-upload" type="text/x-tmpl">

                {% for (var i=0, file; file=o.files[i]; i++) { %}

                <tr class="template-upload fade">
                    <td>
                        <span class="preview"></span>
                    </td>
                    <td>
                        <p class="name">{%=file.name%}</p>
                        <input type="hidden" name="filename[]" value="{%=file.name%}"/>
                        {% if (file.error) { %}
                        <div><span class="label label-danger">Error</span> {%=file.error%}</div>
                        {% } %}
                    </td>
                    <td>
                        <p class="size">{%=o.formatFileSize(file.size)%}</p>
                        {% if (!o.files.error) { %}
                        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
                        {% } %}
                    </td>
                    <td><input type="text" name="order[]" class="span2"/></td>
                    <td>
                        {% if (!o.files.error && !i && !o.options.autoUpload) { %}
                        <button class="btn btn-primary start" style="display:none;">
                           <!-- <i class="glyphicon glyphicon-upload"></i>
                            <span>Enviar</span>-->
                        </button>
                            {% } %}
                            {% if (!i) { %}
                        <button class="btn btn-warning cancel">
                            <i class="glyphicon glyphicon-ban-circle"></i>
                            <span>Cancelar</span>
                        </button>
                        {% } %}
                    </td>
                </tr>
                {% } %}
            </script>
            
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                    <input type="hidden" name="filename[]" value="{%=file.name%}"/>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
		<td><input type="text" name="order[]" class="span2"/></td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %} name="delete-image">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Excluir Imagem</span>
                </button>
              <!--  <input type="checkbox" name="delete" value="1" class="toggle">-->
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancelar</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
		
    
</div>
		
