<div class="row-fluid">
	<div class="span6">		
		<label>Nome:</label>
		<input class="span12" type="text" name="name" />
		<div class="row-fluid">
			<div class="span6">
				<label>SKU:</label>
				<input class="span8" type="text" name="sku" />	
			</div>
			<div class="span6">
				<label>Status:</label>
				<select name="status">
					<option value="1">Ativo</option>
					<option value="0" selected>Desabilitado</option>
				</select>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6">
				<label>Novo Desde:</label>
				<input class="span6 dateme" type="text" name="new_since" value=""/>
			</div>
			<div class="span6">
				<label>Novo Até:</label>
				<input class="span6 dateme" type="text" name="new_until" value=""/>
			</div>
		</div>
			
	</div>	
	<div class="span6">
		<div class="row-fluid">
			<div class="span4">
				<label>Altura (cm):</label><input class="span6" type="text" name="height" />
			</div>
			<div class="span4">
				<label>Largura (cm):</label><input class="span6" type="text" name="width" />
			</div>
			<div class="span4">
				<label>Comprimento (cm):</label><input class="span6" type="text" name="length"/>
			</div>			
		</div>
		<div class="row-fluid">
			<div class="span6">				
				<label>Espessura (cm):</label><input class="span6" type="text" name="thickness" />			
			</div>
			<div class="span6">
				<label>Peso (kg):</label><input class="span6" type="text" name="weight" />
			</div>
		</div>
		
	</div>
	<div class="span3">
		
	</div>
		
</div>
<div class="row-fluid">
	<div class="span12">
		<label>Descrição Resumida:</label>
		<textarea class="span6" rows="3" name="desc1"></textarea>
		<div class="formSep">
			<label>Descrição Técnica:</label>
			<textarea name="desc2" id="wysiwg_full" cols="30" rows="10"></textarea>
		</div>
	</div>
</div>
<script>
        tinymce.init({selector:'textarea#wysiwg_full'});
</script>
