<div class="row-fluid">
	<div class="span8">
		<div class="span6">
			<label><input type="checkbox" name="use_title"/>Usar Titulo do Produto</label>	
			<label>Meta Title:</label>
			<input type="text" name="meta_title"/>
		</div>
	
	</div>
</div>
<div class="row-fluid">
	<div class="span8">
		<div class="span12">
			<label><input type="checkbox" name="use_description"/>Usar Descrição Resumida do Produto</label>				
			<label>Meta Description:</label>
			<textarea name="meta_description" class="span12"></textarea>
		</div>
	</div>
</div>
<div class="row-fluid">
	<div class="span6">
		<label>Mecanismos de Busca:</label>
		<select name="meta_search">
			<option value="1" selected>INDEX, FOLLOW</option>
			<option value="2">NOINDEX, NOFOLLOW</option>
		</select>
	</div>
</div>
