<div class="row-fluid">
	<div class="span6">
		<label>Preço Normal</label>R$
		<input type="text" value="" class="span3 moneyme" name="normal_price"/>
		<label>Preço Promocional</label>R$
		<input type="text" value="" class="span3 moneyme" name="promotional_price"/>
		<label>Promoção De:</label>
		<input type="text" class="span3 dateme" name="promotion_since"/>
		<label>Promoção Até:</label>
		<input type="text" class="span3 dateme" name="promotion_until"/>
	</div>
	<div class="span6">
		<h4 class="heading">Atacado</h4>
		<label>Preço por quantidade</label>
		<div class="row-fluid">
			<div class="span3">
				<label>De:<input class="span6" type="text"/></label>	
			</div>
			<div class="span3">
				<label>Até:<input class="span6" type="text"/></label>
			</div>
			<div class="span3">
				<label>Preço:<input class="span6" type="text"/></label>
			</div>
		</div>
			
				
	</div>
</div>