<div class="row-fluid">
	<div class="span6">
		<label>Preço Normal</label>R$
		<input type="text" value="" class="span3 moneyme" name="normal_price"/>
		<label>Preço Promocional</label>R$
		<input type="text" value="" class="span3 moneyme" name="promotional_price"/>
		<label>Promoção De:</label>
		<input type="text" class="span3 dateme" name="promotion_since"/>
		<label>Promoção Até:</label>
		<input type="text" class="span3 dateme" name="promotion_until"/>
	</div>
	<div class="span6">		
		<div class="row-fluid">
		    <h4 class="heading">Faixas de Preço</h4>
			<div class="span3">           
				<label>De:<input class="span6 numbers" type="text" name="qty_from"/></label>	
			</div>
			<div class="span3">
				<label>Até:<input class="span6 numbers" type="text" name="qty_to"/></label>
			</div>
			<div class="span3">
				<label>Preço:<input class="span6 moneyme" type="text" name="price_range"/></label>
			</div>
			<div class="span2">
			   <a class="price-range-add"><i class="splashy-add"></i></a>
			</div>			
		
		    <div class="span11">
		       <table class="table">
		           <thead>
		              <tr>
		                  <th>De</th>
		                  <th>Até</th>
		                  <th>Preço</th>
		                  <th>Remover</th>
		              </tr>
		           </thead>
		           <tbody id="price-range-table">
		              <tr>
		              
		              </tr>
		           </tbody>		          
		       </table>
		    </div>
		</div>
		<div class="row-fluid">
            <h4 class="heading">Preço Fixo por Grupo</h4>            
            <div class="row-fluid">
            	<div class="span4">
	                <label>Grupo de Clientes</label>
	                <select name="group_clients">
	                    <option value="0">Nenhum</option>
	                    <?php foreach($this->groupClients as $groupClient){?>
	                        <option value="<?php echo $groupClient->getId();?>"><?php echo $groupClient->getName();?></option>
	                    <?php }?>
	                </select>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span4">
	                <label>Preço</label>
	                R$<input type="text" name="group_price" class="span8 moneyme"/>	                
	                	<a class="price-group-add"><i class="splashy-add"></i></a>	                
                </div>                
            </div>
               <div class="span11">
		       <table class="table">
		           <thead>
		              <tr>
		                  <th>Grupo</th>
		                  <th>Preço</th>
		                  <th>Remover</th>		                  
		              </tr>
		           </thead>
		           <tbody id="price-group-table">
		             
		           </tbody>		          
		       </table>
		    </div>
                       
        </div>
	</div>
</div>