<div class="row-fluid">
	<div class="span6">
		<label>Quantidade: </label>
		<input type="text" class="span2" name="qty"/>
		<label>Quantidade Mínima: </label>
		<input type="text"  class="span2" name="minimal_qty"/>
		<label>Mostrar como 'Esgotado' quando a quantidade chegar a:</label>
		<input type="text"  class="span3" name="outstock_qty"/>
		<label>Avisar por email ao Esgotar ou Atingir Qtd Minima?</label>
			<select name="warn_stock" class="span3">
			<option selected value="0">Nenhum</option>
			<option value="1">Ao Esgotar</option>
			<option value="2">Ao Atingir Minimo</option>
		</select>
	</div>
	<div class="span6">
		<label>Quantidade Mínima no Carrinho: </label>
		<input type="text"  class="span2" name="minimal_cart_qty"/>
		<label>Quantidade Máxima no Carrinho: </label>
		<input type="text"  class="span2" name="maximum_cart_qty"/>
		<label>Quantidade Decimal?</label>
		<select name="decimal" class="span3">
			<option selected value="0">Não</option>
			<option value="1">Sim</option>
		</select>
	</div>
	<div class="span6">		
		
	</div>
</div>