<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
      foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>         
<?php }
    
}?>
<div class="modal hide fade" id="viewInvoices">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">×</button>
		<h3>Faturas para Consulta</h3>
	</div>
	<div class="modal-body">
		<table class="table">
			<thead>
				<th>Código</th>
				<th>Última Atualização</th>
			</thead>
			<tbody>
				<?php if(isset($this->invoices)){ 
					foreach($this->invoices as $invoice){ ?>
					<tr>
						<td><a href="/admin238/manage-orders/invoice?view=1&invoiceid=<?= $invoice->getId();?>"><?= $invoice->getInvoiceCod();?></a></td>
						<td><?= $invoice->getDateUpd()->format('d/m/Y - H:i');?></td>
					</tr>
				<?php }
				?>
					
				<?php }?>
			</tbody>			
		</table>
	</div>
	<div class="modal-footer">
		<a class="btn" data-dismiss="modal" href="#">Fechar</a>
	</div>
</div>


<div class="row-fluid">
    <div class="row-fluid">    
        <h1 class="heading">Detalhes do Pedido - #<?= $this->data['general']->getOrderCod();?></h1> 
        <h4>Data: <?= $this->data['general']->getDateCreate()->format('d/m/Y - H:i'); ?></h4>               
        <input type="hidden" id="orderid" value="<?= $this->data['general']->getId();?>"/>
    </div>
    <div class="row-fluid">
    	<div class="span12 pull-left">    		
    		<?php if($this->data['general']->getOrderStatus()->getId() == 1 || $this->data['general']->getOrderStatus()->getId() == 4){?>
	    		<button class="btn pull-left" id="createInvoice">Criar Fatura</button>
	    		<button class="btn pull-left" id="cancelOrder" value="<?= $this->data['general']->getId();?>">Cancelar</button>
    		<?php }?>
    		<?php if($this->data['general']->getOrderStatus()->getId() == 2 || $this->data['general']->getOrderStatus()->getId() == 6){?>
	    		<a data-toggle="modal" data-backdrop="static" href="#viewInvoices"><button class="btn pull-left">Visualizar Fatura(s)</button></a>
	    		<button class="btn pull-left" id="viewShippings">Visualizar Entrega(s)</button>
	    		<button class="btn pull-left" id="reimburse">Reembolsar</button>	    		
    		<?php }?>
    		<?php if($this->data['general']->getOrderStatus()->getId() == 2){ ?>
    			<button class="btn pull-left" id="createShipping">Criar Envio</button>
    		<?php }?>
    		
    		<button class="btn pull-left">Acessar Conta do Cliente</button>
    		
    		<?php if($this->data['general']->getOrderStatus()->getId() != 3){ ?>
    			<button class="btn pull-left" id="sendEmail">Enviar Email</button>
    		<?php }?>
    		<button class="btn">Voltar</button>
    	</div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <h3 class="heading">Dados Gerais</h3>
            <table class="table table-condensed table-striped">                
                <tbody>
                    <tr>
                        <td>Status:</td>                        
                        <td><?= $this->data['general']->getOrderStatus()->getName();?></td>
                    </tr>
                    <tr>
                        <td>Código:</td>
                        <td><?= $this->data['general']->getOrderCod();?></td> 
                    </tr>
                    <tr>
                        <td>Loja:</td>
                        <td><?= $this->data['general']->getStore()->getName();?></td> 
                    </tr>   
                    <tr>
                    	<td>Última Atualização:</td>
                    	<td><?= $this->data['general']->getDateUpd()->format('d/m/Y - H:i');?></td>
                    </tr>                 
                </tbody>
            </table>
        </div>
        <div class="span6">
            <h3 class="heading">Dados do Cliente</h3>
            <table class="table table-condensed table-striped">
                <tbody>
                    <tr>
                        <td>Nome do Cliente:</td>
                        <td><?= $this->client->getFullName();?></td>
                    </tr>
                    <tr>
                        <td>Email:</td>
                        <td><?= $this->client->getEmail();?></td>
                    </tr>
                    <tr>
                        <td>CPF/CNPJ</td>
                        <td><?php if($this->client->getClientType() == 1){echo $this->client->getCpf();}else{echo $this->client->getCnpj();} ?></td>
                    </tr>
                    <tr>
                        <td>Sexo</td>
                        <td><?php if($this->client->getGender() == 0){echo 'Masculino';}else{echo 'Feminino';} ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <h3 class="heading">Itens do Pedido</h3>
            <table class="table table-condensed">
                <?= $this->productTable; ?>
               
            </table>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <h3 class="heading">Endereço de Envio</h3>
                <table class="table table-condensed table-striped">
                    <?php foreach ($this->data['addresses'] as $row){
                        if($row->getAddressType()->getId() == 2){    
                    ?>
                    <tr>
                        <td>Nome Completo:</td>
                        <td><?= $row->getName();?></td>
                    </tr>
                    <tr>
                        <td>Endereço:</td>
                        <td><?= $row->getAddress(); ?></td>
                    </tr>
                    <tr>
                        <td>Número:</td>
                        <td><?= $row->getNumber(); ?></td>
                    </tr>
                    <tr>
                        <td>Complemento:</td>
                        <td><?= $row->getComplement(); ?></td>
                    </tr>
                    <tr>
                        <td>Bairro:</td>
                        <td><?= $row->getDistrict(); ?></td>
                    </tr>
                    <tr>
                        <td>CEP:</td>
                        <td><?= $row->getZipcode(); ?></td>
                    </tr>
                    <tr>
                        <td>Cidade:</td>
                        <td><?= $row->getCity(); ?></td>
                    </tr>
                    <tr>
                        <td>Estado:</td>
                        <td><?= $row->getState()->getName(); ?></td>
                    </tr>
                    <tr>
                        <td>País:</td>
                        <td><?= $row->getCountry()->getName(); ?></td>
                    </tr>
                    <?php }}?>
                </table>
        </div>
        <div class="span6">
            <h3 class="heading">Endereço de Cobrança</h3>
                <table class="table table-condensed table-striped">
                    <?php foreach ($this->data['addresses'] as $row){
                        if($row->getAddressType()->getId() == 3){    
                    ?>
                    <tr>
                        <td>Nome Completo:</td>
                        <td><?= $row->getName();?></td>
                    </tr>
                    <tr>
                        <td>Endereço:</td>
                        <td><?= $row->getAddress(); ?></td>
                    </tr>
                    <tr>
                        <td>Número:</td>
                        <td><?= $row->getNumber(); ?></td>
                    </tr>
                    <tr>
                        <td>Complemento:</td>
                        <td><?= $row->getComplement(); ?></td>
                    </tr>
                    <tr>
                        <td>Bairro:</td>
                        <td><?= $row->getDistrict(); ?></td>
                    </tr>
                    <tr>
                        <td>CEP:</td>
                        <td><?= $row->getZipcode(); ?></td>
                    </tr>
                    <tr>
                        <td>Cidade:</td>
                        <td><?= $row->getCity(); ?></td>
                    </tr>
                    <tr>
                        <td>Estado:</td>
                        <td><?= $row->getState()->getName(); ?></td>
                    </tr>
                    <tr>
                        <td>País:</td>
                        <td><?= $row->getCountry()->getName(); ?></td>
                    </tr>
                    <?php }}?>
                </table>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <h3 class="heading">Forma de Pagamento</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>Moeda</th>
                        <th>Forma</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>BRL</td>
                        <td><?= $this->data['general']->getPaymentType()->getName(); ?></td>
                    </tr>
                    <?php if($this->data['general']->getPaymentType()->getId() == 1 && $this->data['general']->getOrderStatus()->getId() == 1){ ?>
                    <tr>
                        <td><button class="btn" id="generatePagseguroLink">Gerar Link</button></td>
                        <td><input type="text" id="paymentLink" class="span12"/></td>
                        
                    </tr>
                    <?php }?>
                </tbody>
            </table>
        </div>
        <div class="span6">
            <h3 class="heading">Forma de Envio</h3>
                <table class="table">
                    <tr>
                        <td><?= $this->data['general']->getShippingType()->getName();?></td>
                    </tr>
                </table>
        </div>        
    </div>    
    
</div>

<script type="text/javascript">

	$('button#generatePagseguroLink').on('click',function(){
		$('.wait h1').html('Gerando link de pagamento do Pagseguro...');
		$('body').addClass('loading'); 
		var orderid = $('input#orderid').val();
		$.ajax({
	        url: "/pagamento/pagseguro",
	        type:"GET",
	        data:{orderid:orderid},
	        contentType: "application/json; charset=utf-8",
	        dataType:"json",
	        success: function (data) {		        
		       	$('input#paymentLink').val(data);	        
	            $('body').removeClass('loading'); 
	        },
	        error: function(request,error){
	            $('body').removeClass('loading');          
	            console.log(arguments);
	            $.sticky(error, {autoclose : 5000, position: "top-right", type:"st-error" });
	        }
	  });
	});

	$('button#createInvoice').on('click',function(){
		var orderid = $('input#orderid').val();
		window.location.replace('/admin238/manage-orders/invoice?create=1&orderid='+orderid);
	});
    
</script>
