<div class="row-fluid">
	<h1 class="heading">Editar Pedido - #<?= $this->data->getOrderCod();?></h1>	
	<div class="row-fluid">
		<h2 class="heading">Escolha um cliente:</h2>
		<table class="table table-bordered table-striped table_vam customerResults" >
	            <thead>
	                <tr>
	                    <th></th>
	                    <th><input type="text" class="span12" name="searchName" placeholder="Nome..."/></th>
	                    <th><input type="text" class="span12" name="searchEmail" placeholder="Email..."/></th>
	                    <th><input type="text" class="span12" name="searchState" placeholder="Estado..."/></th>
	                    <th><input type="text" class="span12" name="searchCountry" placeholder="País..."/></th>
	                    <th><button class="btn btn-gebo" id="searchCustomer">Buscar</button></th>
	                </tr>
	                <tr>
	                    <th></th>
	                    <th>Nome</th>
	                    <th>Email</th>
	                    <th>Estado</th>
	                    <th>País</th>                 
	                    <th></th>                    
	                </tr>               
	           </thead>
	           <tbody>
	           		<?= $this->clientTable;?>
	           </tbody>  
	    </table>
    	<button class="btn customerSelection" disabled>Próximo Passo</button>
    </div>   
    <div class="row-fluid">
    	
		<div class="row-fluid">
	    	<div id="productSection" style="display:none">
	    		<h2 class="heading">Adicionar Produtos</h2>
			    <table class="table table-bordered table-striped table_vam product-results">
			    	<thead>
			    		<tr>
			    			
			    			<th colspan="3"><input type="text" class="span12" name="productName" placeholder="Nome..."/></th>
		                	<th><input type="text" class="span12" name="productSku" placeholder="SKU..."/></th>
		                	<th colspan="4"><button class="btn btn-gebo" id="searchProduct">Buscar</button></th>
		               </tr>
			    		<tr>
			    			<th class="span1"><input type="checkbox" id="selectAll"/></th>
			    			<th class="span1">Imagem</th>
			    			<th class="span6">Nome do Produto</th>
			    			<th class="span2">SKU</th>
			    			<th>Preço Unitário</th>
			    			<th colspan="2" class="span1">Quantidade</th>
			    			<th>Ação</th>
			    		</tr>
			    		<tr>
			    			<th></th>
			    			<th></th>
			    			<th></th>
			    			<th></th>
			    			<th></th>
			    			<th>Disponível</th>
			    			<th>Pedido</th>
			    			<th></th>
			    		</tr>		    		
			    	</thead>
			    	<tbody id="productResults">		    		
			    	</tbody>
			    </table>
			   
		    </div>
		    <div class="row-fluid">
		    	<div id="productsSelected" style="display:none;">
				        <h2 class="heading">Produtos do Pedido #<?= $this->data->getOrderCod();?></h2>
				        <div class="row-fluid">
				        
				            <table class="table table-bordered table-striped table_vam">
				                <thead>
				                    <tr>
				                        <th class="span12">Nome</th>
				                        <th class="span3">SKU</th>
				                        <th class="span3">Preço</th>
				                        <th class="span3">Qtd</th>
				                        <th class="span3">Total</th>		                        
				                        <th>Remover</th>
				                    </tr>
				                </thead>
				                <tbody></tbody>
				                <tfoot>		                	
				                	<th colspan="4">Total dos Produtos (R$)</th>
				                	<th class="productTotalPrice"></th>
				                </tfoot>
				            </table>
				        </div>
				        <button class="btn productSelection" >Próximo Passo</button>
				</div>
			</div>
			 <div class="row-fluid">
			 	<div id="addressSelection" style="display:none;">
			 		<h2 class="heading">Endereço de Entrega / Cobrança</h2>
			 		<div class="span12">
				 		<div class="span5">
				 			<h4 class="heading">Entrega</h4>
				 			<label>País</label><select class="span6 selectCountry" name="shippingCountry" ><option value="">Escolha</option>
									<?php foreach ($this->countries as $country){?>
									<option value="<?php echo $country->getId(); ?>">
										<?php echo $country->getName(); ?>
									</option>
									<?php } ?></select>
				 			<label>Nome Completo</label><input  class="span12" type="text" name="shippingReceiver"/>
				 			<label>Endereço</label><input  class="span12" type="text" name="shippingAddress"/>
				 			<label>Número</label><input class="span3" type="text" name="shippingNumber"/>
				 			<label>Complemento</label><input class="span4" type="text" name="shippingComplement"/>
				 			<label>Bairro</label><input type="text" class="span8"name="shippingDistrict"/>
				 			<label>CEP</label><input class="span4" type="text" name="shippingZipCode"/>
				 			<label>Cidade</label><input type="text" name="shippingCity"/>
				 			<label>Estado</label><select class="span2" name="shippingState"></select>			 			
				 		</div>
				 		<div class="span5">
				 			<h4 class="heading">Cobrança</h4>
				 			<label>País</label><select class="span6 selectCountry" name="billingCountry" ><option value="">Escolha</option>
									<?php foreach ($this->countries as $country){?>
									<option value="<?php echo $country->getId(); ?>">
										<?php echo $country->getName(); ?>
									</option>
									<?php } ?></select>
				 			<label>Nome Completo</label><input  class="span12" type="text" name="billingReceiver"/>
				 			<label>Endereço</label><input  class="span12" type="text" name="billingAddress"/>
				 			<label>Número</label><input class="span3" type="text" name="billingNumber"/>
				 			<label>Complemento</label><input class="span4" type="text" name="billingComplement"/>
				 			<label>Bairro</label><input type="text" class="span8"name="billingDistrict"/>
				 			<label>CEP</label><input class="span4" type="text" name="billingZipCode"/>
				 			<label>Cidade</label><input type="text" name="billingCity"/>
				 			<label>Estado</label><select class="span2" name="billingState"></select>
				 		</div>
				 	</div>
				 	<button class="btn addressSelection" >Próximo Passo</button>			 		
			 	</div>			 				 
			 </div>
			 <div class="row-fluid">
			 	<div class="span6">
				 	<div id="shipSelection">
				 		<h2 class="heading">Frete</h2>
				 		
				 			<table class="table table-bordered table-striped">
				 				<tr>
				 					<td class="span1"><input type="radio" value=""/></td>
				 					<td class="span6">Correios</td>
				 				</tr>
				 			</table>
				 		
				 	</div>
			 	</div>
			 	<div class="span6">
			 		<div id="paymentSelection">
				 		<h2 class="heading">Forma de Pagamento</h2>
				 		
				 			<table class="table table-bordered table-striped">
				 				<tr>
				 					<td class="span1"><input type="radio" value=""/></td>
				 					<td class="span6">Pagseguro</td>
				 				</tr>
				 			</table>				 			
				 		
				 	</div>				 	
			 	</div>
			 </div>
	    </div>
	</div>
    
</div>
	
</div>

<script type="text/javascript">

function fillAddresses(data){

	$('input[name="shippingReceiver"]').val(data.shipping.receiver);
	$('input[name="shippingAddress"]').val(data.shipping.address);
	$('input[name="shippingNumber"]').val(data.shipping.number);
	$('input[name="shippingComplement"]').val(data.shipping.complement);
	$('input[name="shippingDistrict"]').val(data.shipping.district);
	$('input[name="shippingZipCode"]').val(data.shipping.zipcode);
	$('input[name="shippingCity"]').val(data.shipping.city);
	$('select[name="shippingCountry"]').val(data.shipping.country);
	$.get("/admin238/customer/call-states",{country:$('select[name="shippingCountry"]').val()},function(datas){
    	$("select[name=shippingState]").html(datas);    	
    	$("select[name=shippingState]").val(data.shipping.state);
    });
	

	$('input[name="billingReceiver"]').val(data.billing.receiver);
	$('input[name="billingAddress"]').val(data.billing.address);
	$('input[name="billingNumber"]').val(data.billing.number);
	$('input[name="billingComplement"]').val(data.billing.complement);
	$('input[name="billingDistrict"]').val(data.billing.district);
	$('input[name="billingZipCode"]').val(data.billing.zipcode);
	$('input[name="billingCity"]').val(data.billing.city);
	$('select[name="billingCountry"]').val(data.billing.country);
	$.get("/admin238/customer/call-states",{country:$('select[name="billingCountry"]').val()},function(datas){
    	$("select[name=billingState]").html(datas); 
    	$("select[name=billingState]").val(data.billing.state);   	
    });
	
}

$(document).ready(function(){

			
	$('button#searchCustomer').on('click',function(){
			 
		var name = $('input[name="searchName"]').val();
		var email = $('input[name="searchEmail"]').val();
		var state = $('input[name="searchState"]').val();
		var country = $('input[name="searchCountry"]').val();
		var dateSince = $('input[name="searchSince"]').val();
		var lastLogin = $('input[name="searchLastLogin"]').val();
		var status = $('select[name="searchStatus"]').val();      
		var actions = false;	
		var dates = false;
		var selectType = 'radio';
		
		getClientTable(name,email,state,country,dateSince,lastLogin,status,actions,dates,selectType);
		
	});	

	$('body').on('change','.row_sel',function(){
		$('button.customerSelection').attr('disabled',false);
		var clientid = $(this).val();

		$('.wait h1').html('Aguarde um momento...');
		$('body').addClass('loading');
		
		$.ajax({
	        url: "/admin238/customer/get-addresses",
	        type:"GET",
	        data:{clientid:clientid},
	        contentType: "application/json; charset=utf-8",
	        dataType:"json",
	        success: function (data) {		        
		        fillAddresses(data);		        
	           $('body').removeClass('loading'); 
	        },
	        error: function(request,error){
	            $('body').removeClass('loading');          
	            console.log(arguments);
	            $.sticky(error, {autoclose : 5000, position: "top-right", type:"st-error" });
	        }
	  });
		  
	});
	
	$($('select[name="shippingCountry"]').change(),function(){
		$.get("/admin238/customer/call-states",{country:$('select[name="shippingCountry"]').val()},function(data){
        	$("select[name=shippingState]").html(data);
        	$("select[name=shippingState]").prop('disabled',false);
        });
	});

	$($('select[name="billingCountry"]').change(),function(){
		$.get("/admin238/customer/call-states",{country:$('select[name="billingCountry"]').val()},function(data){
        	$("select[name=billingState]").html(data);
        	$("select[name=billingState]").prop('disabled',false);
        });
	});	
	
	$('button.customerSelection').on('click',function(){
		var i = 0;		
		if($('.row_sel').is(':checked')){
			i++;
		}	
		if(i == 0){
			alert('Você precisa escolher um cliente!');
		}else{			
			$('#productSection').show();
			$(this).hide();
		}
	});	

	$('button.productSelection').on('click',function(){
		$('div#addressSelection').show();
		$(this).hide();
	});

	$('#searchProduct').on('click',function(){
		var name = $('input[name="productName"]').val();
		var sku = $('input[name="productSku"]').val();
		getProductTable(name,sku,1,null,null,null,null,true,null,true,true,true,true);
	});
	
	$('body').on('click','button.addProduct',function(event){	   
	   var i = 0;
	   var productId = $(this).parent().parent().find('input.row_sel').val();
	   var inputQty = $(this).parent().parent().find('input.inputQty').val();
	   var currentQty = $(this).parent().parent().find('td.qty').html();
	   if(inputQty == ''){
	       alert('Preencha uma quantidade!');
	       event.preventDefault();
	       return false;
	   }else if(inputQty > currentQty){
		   alert('Quantidade não disponível!');
	       event.preventDefault();
	       return false;
	   }
	   else{	
		   $('div#productsSelected table tbody').find('input.productid').each(function(event){
			   if($(this).val() == productId){
				   alert('Este produto já consta na seleção do pedido!');
			       event.preventDefault();
			       return false;
			   }
		   });	   
		   var productName = $(this).parent().parent().find('td.productName').html();
		   var productSku = $(this).parent().parent().find('td.productSku').html();
		   var productQty = $(this).parent().parent().find('input.inputQty').val();
		   var productPrice = $(this).parent().parent().find('td.productPrice').html();
		   var productTotal = productPrice.split('R$');
		   var productTotalGeneral = 0;
		   
		   productTotal = productTotal[1] * productQty;		   
		   
		   var content = '<tr><td><input type="hidden" class="span12 productid" value="'+productId+'"/>'+productName+'</td><td>'+productSku+'</td><td>'+productPrice+'</td><td>'+productQty+'</td><td class="productTotal">R$ '+parseFloat(productTotal,10).toFixed(2)+'</td><td><a class="removeProduct"><i class="splashy-gem_remove"></i></a></td></tr>';

	       $('div#productsSelected').show();
	       $('div#productsSelected table tbody').append(content);
	       $('div#productsSelected table tbody').find('td.productTotal').each(function(){
		       var value = $(this).html().split('R$');
		       productTotalGeneral = parseFloat(productTotalGeneral) + parseFloat(value[1]);
		   });
	       $('div#productsSelected table tfoot th.productTotalPrice').html('R$ '+parseFloat(productTotalGeneral,10).toFixed(2));
	   }
	   
	});

	$('body').on('click','a.removeProduct',function(event){
		var valueTotalProduct = $(this).parent().parent().parent().find('td.productTotal').html().split('R$');
		var valueTotalGeneral = $('div#productsSelected table tfoot th.productTotalPrice').html().split('R$');
		var newTotalGeneral = valueTotalGeneral[1] - valueTotalProduct[1];
		$('div#productsSelected table tfoot th.productTotalPrice').html('R$ '+parseFloat(newTotalGeneral,10).toFixed(2));
		$(this).parent().parent().remove();		
		if($('div#productsSelected table tbody').children().length < 1){
			$('div#productsSelected').hide();
		}
	});
});
	
	
</script>