<div class="row-fluid">
	<h1 class="heading">Editar Pedido - #<?= $this->data->getOrderCod();?></h1>	
	<div class="row-fluid">
	Escolha um cliente:
	</div>
	<div class="row-fluid">
	 <table class="table table-bordered table-striped table_vam customerResults" >
            <thead>
                <tr>
                    <th></th>
                    <th><input type="text" class="span12" name="searchName" placeholder="Nome..."/></th>
                    <th><input type="text" class="span12" name="searchEmail" placeholder="Email..."/></th>
                    <th><input type="text" class="span12" name="searchState" placeholder="Estado..."/></th>
                    <th><input type="text" class="span12" name="searchCountry" placeholder="País..."/></th>
                    
                    <th><button class="btn btn-gebo" id="searchCustomer">Buscar</button></th>
                </tr>
                <tr>
                    <th></th>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Estado</th>
                    <th>País</th>                 
                    <th></th>
                    
                </tr>
           </thead>
           <tbody>
           	<?= $this->clientTable;?>
           </tbody>  
    </table>
    </div>
	
</div>