<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
      foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>         
<?php }
    
}?>

<div class="row-fluid">
	<div class="span12">
		<h1 class="heading">Gerenciar Pedidos<button class="btn add-new">Criar Pedido</button></h1>
		<div class="row-fluid">
			<div class="span2">
				<div class="dt_actions">
					<div class="btn-group">
						<button class="btn dropdown-toggle" data-toggle="dropdown">Ações em Massa <span class="caret"></span></button>
							<ul class="dropdown-menu">
								<li><a onclick="cancelOrder()" class="select_rows">Cancelar</a></li>								
							</ul>
					</div>			
				</div>						
			</div>
			<div class="span1">		
				<select name="maxPages" class="span12">
					<option value="2">1</option>
					<option value="3">3</option>
					<option value="5">5</option>
				</select>
			</div>		
		</div>
		<div class="row-fluid paginator">
			<?php echo $this->pagination;?>
		</div>
		<table class="table table-striped table-bordered dTableR order-results" >
			<thead>
				<tr>
					<th class="table_checkbox"><input type="checkbox"
                        name="select_rows" class="select_rows" data-tableid="dt_gal" /></th>
                    <th class="span1">ID</th>
					<th class="span1">Pedido</th>
					<th class="span1">Cliente</th>
					<th class="span1">Data</th>
					<th class="span1">Atualizado</th>					
					<th class="span1">Valor</th>
					<th class="span2">Status</th>
					<th class="span1">Ação</th>
				</tr>
				<tr>
					<th></th>
					<th></th>
					<th><input type="text" class="span12" name="searchOrder" placeholder="Pedido..."/></th>
					<th><input type="text" class="span12" name="searchClient" placeholder="Cliente..."/></th>
					<th><input type="text" class="span12 date" name="searchDate" placeholder="Data..."/></th>
					<th><input type="text" class="span12 date" name="searchLastUpd" placeholder="Atualizado em"/></th>
					<th>						
						<input type="text" class="span12" name="searchValue" placeholder="Valor..."/>
					</th>
					<th>
						<select class="span12" name="searchStatus">
						    <option value="" selected>Escolha...</option>
							<?php foreach($this->status as $status){ ?>
								<option value="<?= $status->getId();?>"><?= $status->getName(); ?></option>
							<?php }?>
						</select>
					</th>
					<th><button class="btn btn-gebo" id="search">Buscar</button></th>
				</tr>
			</thead>
			<?= $this->table; ?>
		</table>
		
		<div class="row-fluid paginator">
			<?php echo $this->pagination;?>
		</div>
	</div>
</div>

<script type="text/javascript">

    $('a, button').bind('touchend', function(e) {
        $(this).trigger('click');
        e.preventDefault();
    });
    $('button.add-new').on('click',function(){
		 var accept = confirm('Deseja criar um novo pedido?');
		 if(accept){
			 window.location.replace("/admin238/manage-orders/add?create"); 
		 }else{
			 e.preventDefault();
			 return false;
		 }
	});	
	
	$('button#search').on('click',function(){
	    
	    $('.wait h1').html('Buscando pedidos...');
        $('body').addClass('loading');
        
        var name = '';
        var cod = '';
        var status = '';
        var datecreate = '';
        var value = '';
        
        if($('input[name="searchOrder"]').val() != ''){
            cod = $('input[name="searchOrder"]').val();
        }
        if($('input[name="searchClient"]').val() != ''){
            name = $('input[name="searchClient"]').val();
        }
        if($('input[name="searchDate"]').val() != ''){
            datecreate = $('input[name="searchDate"]').val();
        }
        if($('input[name="searchValue"]').val() != ''){
            value = $('input[name="searchValue"]').val();
        }
        if($('select[name="searchStatus"]').val() != ''){
            status = $('select[name="searchStatus"]').val();
        }
        $.ajax({
                        url: "/admin238/manage-orders/filter-orders",
                        type:"GET",
                        data:{
                            client:name,                            
                            ordercod:cod,
                            orderstatus:status,
                            value:value,
                            datecreate:datecreate                          
                        },
                        contentType: "application/json; charset=utf-8",
                        dataType:"json",
                        success: function (data) {              
                             $('table.order-results tbody').remove();
                             $('div.paginator').empty();
                             $('table.order-results').append(data.results);
                             $('div.paginator').append(data.pagination);
                             $('body').removeClass('loading');
                        },
                        error: function(request,error){
                            console.log(arguments);
                            $.sticky(error, {autoclose : 5000, position: "top-right", type:"st-error" });
                        }
                });
        
    });
    
	$('button.details').on('click',function(){
        window.location.replace("/admin238/manage-orders/details?orderid="+$(this).parent().parent().find('td input').val()); 
    });
	
	$('button.rebuy').on('click',function(){
		
	});
	$('button.edit').on('click',function(){
	    window.location.replace("/admin238/manage-orders/edit?orderid="+$(this).parent().parent().find('td input').val());
	});
	$('button.remove').on('click',function(e){
	    
		 var accept = confirm('Deseja mesmo remover este pedido?');
		 if(accept){
			 var orderId = $(this).attr('value');
			 window.location.replace("/admin238/manage-orders/remove?orderid=" + orderId); 
		 }else{
			 e.preventDefault();
			 return false;
		 }
	});
	$('button.send').on('click',function(){
		
		$.ajax({
                        url: "/admin238/manage-orders/save",
                        type:"GET",
                        data:{
                            orderId:orderId,
                            clientId:clientId,
                            productsId:productsId, 
                            productsQtd:productsQtd,
                            unitsPrice:unitsPrice,
                            updateAddress: 1,
                            shippingName : shippingName,
                            shippingAddress : shippingAddress,
                            shippingNumber : shippingNumber,
                            shippingComplement : shippingComplement,
                            shippingZipcode : shippingZipcode,
                            shippingDistrict : shippingDistrict,
                            shippingCity : shippingCity,
                            shippingState : shippingState,
                            shippingCountry : shippingCountry,
                            billingName : billingName,
                            billingAddress : billingAddress,
                            billingNumber : billingNumber,
                            billingComplement : billingComplement,
                            billingZipcode : billingZipcode,
                            billingDistrict : billingDistrict,
                            billingCity : billingCity,
                            billingState : billingState,
                            billingCountry : billingCountry,
                            freightType: shippingType,
                            freightCost: freightCost,
                            productPrice: parseFloat(productTotalPrice[1]),
                            totalPrice: totalPrice,
                            shippingType: shippingType,
                            paymentType: paymentType,
                            gift: gift,
                            giftMsg: giftMsg,
                            orderStatus: 1                          
                        },
                        contentType: "application/json; charset=utf-8",
                        dataType:"json",
                        success: function (data) {              
                             if(data == true){                               
                                 window.location.replace('/admin238/manage-orders'); 
                             }
                        },
                        error: function(request,error){
                            console.log(arguments);
                            $.sticky(error, {autoclose : 5000, position: "top-right", type:"st-error" });
                        }
                });
		
	});
	
	$('body').on('click','input.select_rows',function(){
	    if($(this).prop('checked') != false){
    	    $('input.orderid').each(function(){
    	        $(this).prop('checked',true);    
    	    });
	    }else{
	        $('input.orderid').each(function(){
                $(this).prop('checked',false);    
            });
	    }
	});
	
	function cancelOrder(){
		
		var count = 0;
		$('input.orderid').each(function(){
	        if($(this).prop('checked') == true){
	            count++;
	        }
	    });
	    if(count > 0){
		    var accept = confirm('Deseja mesmo cancelar este(s) pedido(s)?');
		    if(accept){
		        var url = '/admin238/manage-orders/cancel?';
	    	    var orders = '';
	    	    $('input.orderid').each(function(){
	    	        if($(this).prop('checked') == true){
	    	            orders = orders + '&orderid[]=' + $(this).val();
	    	        }
	    	    });
	    	    url = url + orders;
	    	    var updatestock = confirm('Deseja retornar itens ao estoque?');
	    	    if(updatestock){
	    	        url = url + '&updatestock=1';
	    	    }
	    	    window.location.replace(url);
		    } 
	    }else{
		    alert('Selecione um pedido!'); 
	    }
	}
		
</script>