<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
      foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>         
<?php }
    
}?>

<div class="row-fluid">
	<div class="span12">
		<h1 class="heading">Gerenciar Pedidos<button class="btn add-new"><a href="/admin238/manage-orders/add">Criar Pedido</a></button></h1>
		<div class="row-fluid">
			<div class="span2">
				<div class="dt_actions">
					<div class="btn-group">
						<button class="btn dropdown-toggle" data-toggle="dropdown">Ações em Massa <span class="caret"></span></button>
							<ul class="dropdown-menu">
								<li><a href="javascript:void(0)" class="select_rows">Selecionar Tudo</a></li>
								<li><a href="javascript:void(0)" class="deselect_rows">Deselecionar Tudo</a></li>
							</ul>
					</div>			
				</div>						
			</div>
			<div class="span1">		
				<select name="maxPages" class="span12">
					<option value="2">1</option>
					<option value="3">3</option>
					<option value="5">5</option>
				</select>
			</div>		
		</div>
		<div class="row-fluid paginator">
			<?php echo $this->pagination;?>
		</div>
		<table class="table table-striped table-bordered dTableR order-results" >
			<thead>
				<tr>
					<th class="table_checkbox"><input type="checkbox"
                        name="select_rows" class="select_rows" data-tableid="dt_gal" /></th>
					<th class="span2">Pedido</th>
					<th class="span1">Data</th>
					<th class="span1">Atualizado</th>
					<th class="span2">Cliente</th>
					<th class="span1">Valor</th>
					<th class="span2">Status</th>
					<th class="span1">Ação</th>
				</tr>
				<tr>
					<th></th>
					<th><input type="text" class="span12" name="searchOrder" placeholder="Pedido..."/></th>
					<th><input type="text" class="span12 date" name="searchDate" placeholder="Data..."/></th>
					<th><input type="text" class="span12 date" name="searchLastUpd" placeholder="Atualizado em"/></th>
					<th><input type="text" class="span12" name="searchCustomer" placeholder="Cliente..."/></th>
					<th>						
						<input type="text" class="span12" name="searchValueTo" placeholder="Para..."/>
					</th>
					<th>
						<select class="span12" name="searchStatus">
							<?php foreach($this->status as $status){ ?>
								<option value="<?= $status->getId();?>"><?= $status->getName(); ?></option>
							<?php }?>
						</select>
					</th>
					<th><button class="btn btn-gebo" id="search">Buscar</button></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->orders as $order){
					$status = $order->getOrderStatus()->getId();
					$actions = '';				
					$status = 3;
				if($status === 1 || $status === 2 || $status === 4){
					if($status === 1 || $status === 4){
						$actions .= '<button class="btn span12">Aprovar</button>';
					}
					if($status === 2){
						$actions .= '<button class="btn span12">Enviar</button>';
					}
					$actions .= '<button class="btn span12">Cancelar</button>';
				}
				if($status === 3 || $status === 5){
					$actions .= '<button class="btn span12">Recomprar</button>';
				}
				?>
				<tr>
					<td></td>
					<td>#<?= $order->getOrderCod(); ?></td>
					<td><?= $order->getDateCreate()->format('d/m/Y - H:i');?></td>
					<td><?= $order->getDateUpd()->format('d/m/Y - H:i');?></td>
					<td><?= $order->getClient()->getFirstName() . ' ' . $order->getClient()->getLastName(); ?></td>
					<td>R$ <?= $order->getValue(); ?></td>
					<td><?= $order->getOrderStatus()->getName(); ?></td>
					<td><?= $actions;?></td>
				</tr>
				<?php }?>
			</tbody>
		</table>
	</div>
</div>