<div class="row-fluid">
    <div class="row-fluid">    
        <h1 class="heading"><?= $this->title;?> - Pedido <?= $this->data['general']->getOrderCod();?></h1> 
     	<input type="hidden" id="orderid" value="<?= $this->data['general']->getId();?>"/>
     </div>
     <div class="row-fluid">
    	<div class="span12 pull-left">
    		
    			<!-- <button class="btn pull-left" id="sendInvoice">Enviar Fatura por Email</button> -->
    		<button class="btn pull-left" class="saveInvoice">Salvar Fatura</button>
    		<!--<button class="btn pull-left" id="printInvoice">Imprimir</button> -->
    		<button class="btn pull-left">Acessar Conta do Cliente</button>
    		
    		<button class="btn">Voltar</button>
    	</div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <h3 class="heading">Dados do Pedido</h3>
            <table class="table table-condensed table-striped">                
                <tbody>
                	<tr>
                		<td>Data:</td>
                		<td><?= $this->data['general']->getDateCreate()->format('d/m/Y - H:i')?></td>
                	</tr>
                    <tr>
                        <td>Status:</td>                        
                        <td><?= $this->data['general']->getOrderStatus()->getName();?></td>
                    </tr>
                    <tr>
                        <td>Código:</td>
                        <td><?= $this->data['general']->getOrderCod();?></td> 
                    </tr>
                    <tr>
                        <td>Loja:</td>
                        <td><?= $this->data['general']->getStore()->getName();?></td> 
                    </tr>                    
                </tbody>
            </table>
        </div>
        <div class="span6">
            <h3 class="heading">Dados do Cliente</h3>
            <table class="table table-condensed table-striped">
                <tbody>
                    <tr>
                        <td>Nome do Cliente:</td>
                        <td><?= $this->client->getFullName();?></td>
                    </tr>
                    <tr>
                        <td>Email:</td>
                        <td><?= $this->client->getEmail();?></td>
                    </tr>
                    <tr>
                        <td>CPF/CNPJ</td>
                        <td><?php if($this->client->getClientType() == 1){echo $this->client->getCpf();}else{echo $this->client->getCnpj();} ?></td>
                    </tr>
                    <tr>
                        <td>Sexo</td>
                        <td><?php if($this->client->getGender() == 0){echo 'Masculino';}else{echo 'Feminino';} ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <h3 class="heading">Itens do Pedido</h3>
            <table class="table table-condensed">
                <?= $this->productTable; ?>
               
            </table>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <h3 class="heading">Endereço de Envio</h3>
                <table class="table table-condensed table-striped">
                    <?php foreach ($this->data['addresses'] as $row){
                        if($row->getAddressType()->getId() == 2){    
                    ?>
                    <tr>
                        <td>Nome Completo:</td>
                        <td><?= $row->getName();?></td>
                    </tr>
                    <tr>
                        <td>Endereço:</td>
                        <td><?= $row->getAddress(); ?></td>
                    </tr>
                    <tr>
                        <td>Número:</td>
                        <td><?= $row->getNumber(); ?></td>
                    </tr>
                    <tr>
                        <td>Complemento:</td>
                        <td><?= $row->getComplement(); ?></td>
                    </tr>
                    <tr>
                        <td>Bairro:</td>
                        <td><?= $row->getDistrict(); ?></td>
                    </tr>
                    <tr>
                        <td>CEP:</td>
                        <td><?= $row->getZipcode(); ?></td>
                    </tr>
                    <tr>
                        <td>Cidade:</td>
                        <td><?= $row->getCity(); ?></td>
                    </tr>
                    <tr>
                        <td>Estado:</td>
                        <td><?= $row->getState()->getName(); ?></td>
                    </tr>
                    <tr>
                        <td>País:</td>
                        <td><?= $row->getCountry()->getName(); ?></td>
                    </tr>
                    <?php }}?>
                </table>
        </div>
        <div class="span6">
            <h3 class="heading">Endereço de Cobrança</h3>
                <table class="table table-condensed table-striped">
                    <?php foreach ($this->data['addresses'] as $row){
                        if($row->getAddressType()->getId() == 3){    
                    ?>
                    <tr>
                        <td>Nome Completo:</td>
                        <td><?= $row->getName();?></td>
                    </tr>
                    <tr>
                        <td>Endereço:</td>
                        <td><?= $row->getAddress(); ?></td>
                    </tr>
                    <tr>
                        <td>Número:</td>
                        <td><?= $row->getNumber(); ?></td>
                    </tr>
                    <tr>
                        <td>Complemento:</td>
                        <td><?= $row->getComplement(); ?></td>
                    </tr>
                    <tr>
                        <td>Bairro:</td>
                        <td><?= $row->getDistrict(); ?></td>
                    </tr>
                    <tr>
                        <td>CEP:</td>
                        <td><?= $row->getZipcode(); ?></td>
                    </tr>
                    <tr>
                        <td>Cidade:</td>
                        <td><?= $row->getCity(); ?></td>
                    </tr>
                    <tr>
                        <td>Estado:</td>
                        <td><?= $row->getState()->getName(); ?></td>
                    </tr>
                    <tr>
                        <td>País:</td>
                        <td><?= $row->getCountry()->getName(); ?></td>
                    </tr>
                    <?php }}?>
                </table>
        </div>
        <div class="row-fluid">
        <div class="span6">
            <h3 class="heading">Forma de Pagamento</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>Moeda</th>
                        <th>Forma</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>BRL</td>
                        <td><?= $this->data['general']->getPaymentType()->getName(); ?></td>
                    </tr>                  
                </tbody>
            </table>
        </div>
        <div class="span6">
            <h3 class="heading">Forma de Envio</h3>
                <table class="table">
                    <tr>
                        <td><?= $this->data['general']->getShippingType()->getName();?></td>
                    </tr>
                </table>
        </div>        
    </div>
   <div class="row-fluid">   
   		<div class="span6 pull-right">
   			<div class="row-fluid">   				
   					<h3 class="heading">Informações Adicionais da Fatura</h3>
   					<textarea class="span12" name="invoiceComment"></textarea>   				
   			</div>
		    <div class="row-fluid">
		    	<div class="pull-right">
		    		<input type="checkbox"/> Enviar Fatura por Email ao Cliente
		    	</div>    	
		    </div>
		     <div class="row-fluid">
		    	<div class="pull-right">
		    		<button class="btn" class="saveInvoice">Salvar Fatura</button>
		    	</div>    	
		    </div>
	    </div>
    </div>
</div>