<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
      foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>         
<?php }
    
}?>

<div class="row-fluid">
	<div class="row-fluid">  
		<h1 class="heading">Gerenciar Entregas</h1>
	</div>
	<div class="row-fluid paginator">
        <?php echo $this->pagination;?>
    </div>
    <table class="table">
    	<thead>
    		<th>Pedido</th>
    		<th>Cód. Envio</th>
    		<th>Frete Adquirido</th>
    		<th>Data do Envio</th>
    		<th></th>
    	</thead>
    	<tbody>
    		<tr>				
				<td><input type="text" name="search_order" value="" class="span12"/></td>
				<td><input type="text" name="search_shipping" value="" class="span12"/></td>
				<td>
					<select name="search_type">
						<?php foreach($this->shippingTypes as $shippingType){?>
							<option value="<?= $shippingType->getId();?>"><?= $shippingType->getName();?></option>
						<?php }?>
					</select>				
				</td>
				<td><input type="text" name="search_date" value="" class="span12"/></td>
				<td><button class="btn search">Buscar</button></td>
			</tr>
			<?php foreach ($this->shippings as $shipping){ ?>
				<tr>
					<td><?= $shipping->getOrder()->getOrderCod();?></td>
					<td><?= $shipping->getShippingCod();?></td>
					<td><?= $shipping->getOrder()->getShippingType()->getName();?></td>
					<td><?= $shipping->getDateCreate()->format('d/m/Y - H:i');?></td>
				</tr>
			<?php }?>
    	</tbody>
    </table>
	<div class="row-fluid paginator">
        <?php echo $this->pagination;?>
    </div>
</div>