<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
      foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>         
<?php }
    
}?>

<div class="row-fluid">
	<div class="row-fluid">  
		<h1 class="heading">Gerenciar Entregas</h1>
	</div>
	<div class="row-fluid paginator">
        <?php echo $this->pagination;?>
    </div>
    <table class="table" id="shipping-results">
    	<thead>
    		<tr>
	    		<th>Pedido</th>
	    		<th>Cód. Envio</th>
	    		<th>Frete Adquirido</th>
	    		<th>Data do Envio</th>
	    		<th></th>	    		
    		</tr>
    		<tr>				
				<th><input type="text" name="search_order" value="" class="span12"/></th>
				<th><input type="text" name="search_shipping" value="" class="span12"/></th>
				<th>
					<select name="search_type">
						<?php foreach($this->shippingTypes as $shippingType){?>
							<option value="<?= $shippingType->getId();?>"><?= $shippingType->getName();?></option>
						<?php }?>
					</select>				
				</th>
				<th><input type="text" name="search_date" value="" class="span12 date"/></th>
				<th><button class="btn search">Buscar</button></th>
			</tr>
    	</thead>
    <!-- 	<tbody>
    		
			<?php foreach ($this->shippings as $shipping){ ?>
				<tr>
					<td><a href="/admin238/manage-orders/details?orderid=<?= $shipping->getOrder()->getId();?>"><?= $shipping->getOrder()->getOrderCod();?></a></td>
					<td><a href="/admin238/manage-orders/shipping?orderid=<?= $shipping->getOrder()->getId();?>&shippingid=<?= $shipping->getId();?>"><?= $shipping->getShippingCod();?></a></td>
					<td><?= $shipping->getOrder()->getShippingType()->getName();?></td>
					<td><?= $shipping->getDateCreate()->format('d/m/Y - H:i');?></td>
				</tr>
			<?php }?>
    	</tbody>-->
    	<?= $this->shippings;?>
    </table>
	<div class="row-fluid paginator">
        <?php echo $this->pagination;?>
    </div>
</div>

<script type="text/javascript">
    
    $('button.search').on('click',function(){
        
        var ordercod = '';
        var shippingcod = '';
        var shippingtype = '';
        var dateship = '';
        
        if($('input[name="search_order"]').val() != ''){
            ordercod = $('input[name="search_order"]').val();
        }
        if($('input[name="search_shipping"]').val() != ''){
            shippingcod = $('input[name="search_shipping"]').val();
        }
        if($('select[name="search_shipping"]').val() != ''){
            shippingtype = $('select[name="search_type"]').val();
        }
        if($('input[name="search_date"]').val() != ''){
            dateship = $('input[name="search_date"]').val();
        }
        
        $.ajax({
            url: "/admin238/manage-orders/list-shippings",
            type:"GET",
            data:{
                json:1,
                ordercod:ordercod,
                shippingcod:shippingcod,
                shippingtype:shippingtype,
                dateship:dateship                         
            },
            contentType: "application/json; charset=utf-8",
            dataType:"json",
            success: function (data) {              
                             $('table#shipping-results tbody').remove();
                             $('div.paginator').empty();
                             $('table#shipping-results').append(data.results);
                             $('div.paginator').append(data.pagination);
                             $('body').removeClass('loading');
                        },
            error: function(request,error){
                console.log(arguments);
                $.sticky(error, {autoclose : 5000, position: "top-right", type:"st-error" });
            }
         });
        
    });
    
</script>
