<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
      foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>         
<?php }
    
}?>

<div class="row-fluid">
	<div class="row-fluid">  
	    <?php if(!isset($this->shipping)){?>  
            <h1 class="heading">Criar Envio - Pedido #<?= $this->data['general']->getOrderCod()?></h1>
        <?php }else{ ?>
             <h1 class="heading">Entrega do Pedido #<?= $this->data['general']->getOrderCod()?></h1>
        <?php }?>
     	<input type="hidden" id="orderid" value="<?= $this->data['general']->getId();?>"/>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <?php if(!isset($this->shipping)){?>  
            <h3 class="heading">Dados do Pedido</h3>
            <table class="table table-condensed table-striped">                
                <tbody>
                	<tr>
                		<td>Data do Pedido:</td>
                		<td><?= $this->data['general']->getDateCreate()->format('d/m/Y - H:i');?></td>
                	</tr>
                	<tr>
                        <td>Código do Pedido:</td>
            <?php }else{?>
            <h3 class="heading">Dados da Entrega</h3>
            <table class="table table-condensed table-striped">                
                <tbody>
                    <tr>
                        <td>Data do Pedido:</td>
                        <td><?= $this->data['general']->getDateCreate()->format('d/m/Y - H:i');?></td>
                    </tr>
                    <tr>
                        <td>Data do Envio:</td>
                        <td><?= $this->shipping->getDateCreate()->format('d/m/Y - H:i');?></td>
                    </tr>
                    <tr>
                        <td>Código do Envio:</td>
                        <td><?= $this->shipping->getShippingCod();?></td>
                    </tr>
                    <tr>
                        <td>Código do Pedido:</td>    
            <?php } ?>
                        <td>#<?= $this->data['general']->getOrderCod();?></td> 
                    </tr>
                    <tr>
                        <td>Status:</td>                        
                        <td><?= $this->data['general']->getOrderStatus()->getName();?></td>
                    </tr>                    
                    <tr>
                        <td>Loja:</td>
                        <td><?= $this->data['general']->getStore()->getName();?></td> 
                    </tr>                    
                </tbody>
            </table>
        </div>
        <div class="span6">
            <h3 class="heading">Dados do Cliente</h3>
            <table class="table table-condensed table-striped">
                <tbody>
                    <tr>
                        <td>Nome do Cliente:</td>
                        <td><?= $this->client->getFullName();?></td>
                    </tr>
                    <tr>
                        <td>Email:</td>
                        <td><?= $this->client->getEmail();?></td>
                    </tr>
                    <tr>
                        <td>CPF/CNPJ</td>
                        <td><?php if($this->client->getClientType() == 1){echo $this->client->getCpf();}else{echo $this->client->getCnpj();} ?></td>
                    </tr>
                    <tr>
                        <td>Sexo</td>
                        <td><?php if($this->client->getGender() == 0){echo 'Masculino';}else{echo 'Feminino';} ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="row-fluid">
	        <div class="span12">
	            <h3 class="heading">Endereço de Envio</h3>
	                <table class="table table-condensed table-striped">
	                    <?php foreach ($this->data['addresses'] as $row){
	                        if($row->getAddressType()->getId() == 2){    
	                    ?>
	                    <tr>
	                        <td>Nome Completo:</td>
	                        <td><?= $row->getName();?></td>
	                    </tr>
	                    <tr>
	                        <td>Endereço:</td>
	                        <td><?= $row->getAddress(); ?></td>
	                    </tr>
	                    <tr>
	                        <td>Número:</td>
	                        <td><?= $row->getNumber(); ?></td>
	                    </tr>
	                    <tr>
	                        <td>Complemento:</td>
	                        <td><?= $row->getComplement(); ?></td>
	                    </tr>
	                    <tr>
	                        <td>Bairro:</td>
	                        <td><?= $row->getDistrict(); ?></td>
	                    </tr>
	                    <tr>
	                        <td>CEP:</td>
	                        <td><?= $row->getZipcode(); ?></td>
	                    </tr>
	                    <tr>
	                        <td>Cidade:</td>
	                        <td><?= $row->getCity(); ?></td>
	                    </tr>
	                    <tr>
	                        <td>Estado:</td>
	                        <td><?= $row->getState()->getName(); ?></td>
	                    </tr>
	                    <tr>
	                        <td>País:</td>
	                        <td><?= $row->getCountry()->getName(); ?></td>
	                    </tr>
	                    <?php }}?>
	                </table>
	        </div>
        </div>
        <div class="row-fluid">
	        <div class="span12">
	            <?php if(!isset($this->shipping)){?>  
	            <h3 class="heading">Itens a Enviar</h3>
	            <?php }else{?>
	            <h3 class="heading">Itens Enviados</h3>
	            <?php }?>
	            <table class="table table-condensed">
	                <?= $this->productTable; ?>	               
	            </table>
	        </div>
    	</div>
    	<div class="row-fluid">
	    	<div class="span6">
	            <h3 class="heading">Forma de Envio</h3>
	                <?= $this->data['general']->getShippingType()->getName();?>	                
	        </div> 
	        <div class="span6">
	        	<h3 class="heading">Código de Rastreio</h3>
	        	<table class="table" id="trackingnumbers">
	        		<thead>
	        			<th>Transportadora</th>
	        			<th>Código</th>
	        		</thead>
	        		<tbody>
	        		    <?php if(!isset($this->trackings)){ ?>
		        		<tr class="tracking_row">
		        			<td>
		        				<select class="span12" name="carrier">
		        					<?php foreach ($this->shippingTypes as $type){ ?>
		        					<option value="<?= $type->getId();?>"><?= $type->getName(); ?></option>
		        					<?php }?>
		        				</select>
		        			</td>
		        			<td><input type="text" class="trackingNumber span12" value=""/></td>		        			
		        		</tr>
		        		<?php }else{
		        		    if(isset($this->trackings)){
		        		   foreach($this->trackings as $tracking){ 
		        		?>
		        		<tr class="tracking_row">
                            <td>
                                <select class="span12" name="carrier">
                                    <?php foreach ($this->shippingTypes as $type){ ?>
                                    <option value="<?= $type->getId();?>" <?php if($tracking->getShippingType()->getId() == $type->getId()){echo 'selected';}?>><?= $type->getName(); ?></option>
                                    <?php }?>
                                </select>
                            </td>
                            <td><input type="text" class="trackingNumber span12" value="<?= $tracking->getTrackingNumber();?>"/></td>                            
                        </tr>    
		        		<?php }} }?>
	        		</tbody>
	        	</table>
	        	<button class="btn" id="addtracking">Adicionar Outro Código</button>
	        </div>
    	</div> 
    	<div class="row-fluid">
    		<div class="span6">
    			<h3 class="heading">Comentários</h3>
    			<textarea name="shipping_comment" class="span12"></textarea>
    		</div>
    		<div class="span6">
    			<div class="row-fluid"></div>
    			<?php if(!isset($this->shipping)){ ?>
    			<div class="row-fluid">
    				<label class="pull-right">
    					<input type="checkbox" name="send_email"/> Enviar email ao cliente
    				</label>
    			</div>    			
    			    <div class="row-fluid"><button class="btn pull-right" id="createShipping">Enviar</button></div>
    			<?php }else{ ?>
    			    <div class="row-fluid">
    			        <button class="btn pull-right" id="saveShipping">Salvar</button>
    			        <button class="btn pull-right" id="sendtoClient">Enviar Rastreio ao Cliente</button>
    			    </div>
    			<?php }?>
    		</div>
    	</div>    
</div>

<script type="text/javascript">
	                    
	$('button#addtracking').on('click',function(){	
		
		$('tr.tracking_row').wrap('<p>');
		var x = $('table#trackingnumbers tbody p:first-child');
		$('table#trackingnumbers tbody').append(x.html());	
		$('p tr.tracking_row').unwrap();
				
	});
	
	$('button#saveShipping').on('click',function(){ 
	    var accept = confirm('Deseja salvar as informações de rastreio?');
	    if(accept){
	        $('.wait h1').html('Salvando dados de rastreamento...');
            $('body').addClass('loading'); 
            
            var shippingType = new Array();
            var tracking = new Array();
            var a = 0;
            $('input.trackingNumber').each(function(){
               
                if($(this).val() != ''){
                    shippingType[a] = $(this).parent().parent().find('select[name="carrier"]').val();
                    tracking[a] = $(this).val();
                    a++;
                }
            }); 
           var orderid = $('input#orderid').val();
           <?php if(isset($this->shipping)){ ?> var shippingid = <?php echo $this->shipping->getId();} ?>;
           
                    $.ajax({
                        url: "/admin238/manage-orders/shipping",
                        type:"GET",
                        data:{
                            updatetracking:1, 
                            shippingid:shippingid,
                            shippingType:shippingType,
                            tracking:tracking},
                        contentType: "application/json; charset=utf-8",
                        dataType:"json",
                        success: function (data) {              
                            window.location.replace('/admin238/manage-orders/details?orderid='+orderid);                            
                            $('body').removeClass('loading'); 
                        	
                        },
                        error: function(request,error){
                            $('body').removeClass('loading');          
                            console.log(arguments);
                            $.sticky(error, {autoclose : 5000, position: "top-right", type:"st-error" });
                        }
                    });
            
	    }
	});

	$('button#createShipping').on('click',function(){
		var count = 0;
		$('input.qtyShipping').each(function(){
			count += Number($(this).val());
		});
		if(count > 0){
			var accept = confirm('Confirma envio do pedido?');
			
				if(accept){
					
					$('.wait h1').html('Gerando envio do pedido...');
					$('body').addClass('loading'); 
					
					var orderid = $('input#orderid').val();
					var comment = $('textarea[name="shipping_comment"]').val();
					var emailSent = 0;
					
					if($('input[name="send_email"]').prop('checked') == true){
						emailSent = 1;
					}

					// Relaciona os itens a serem enviados (pendente)
				/*	var itemsId = new Array();
					var itemsQty = new Array();
					var i = 0;					
					$('input.qtyShipping').each(function(){
						if($(this).val() != 0){
							itemsQty[i] = $(this).val();
							itemsId[i] = $(this).parent().parent().find('input.productid').val();
							i++;
						}						
					});*/

					// Relaciona os códigos de rastreio
					var shippingType = new Array();
					var tracking = new Array();
					var a = 0;
					$('input.trackingNumber').each(function(){
						if($(this).val() != ''){
							shippingType[a] = $(this).parent().parent().find('select[name="carrier"]').val();
							tracking[a] = $(this).val();
							a++;
						}
					});				
					
					$.ajax({
				        url: "/admin238/manage-orders/save-shipping",
				        type:"GET",
				        data:{
					        orderid:orderid, 
					        comment:comment, 
					        sendemail:emailSent, 
					     //   itemsId:itemsId,
					    //    itemsQty:itemsQty,
					        shippingType:shippingType,
					        tracking:tracking},
				        contentType: "application/json; charset=utf-8",
				        dataType:"json",
				        success: function (data) {		        
					       	window.location.replace('/admin238/manage-orders/details?orderid='+orderid);		       		        
				            $('body').removeClass('loading'); 
				        },
				        error: function(request,error){
				            $('body').removeClass('loading');          
				            console.log(arguments);
				            $.sticky(error, {autoclose : 5000, position: "top-right", type:"st-error" });
				        }
				    });
				}
			}else{			
				var error = 'Você não selecionou nenhum produto para enviar!';
				$.sticky(error, {autoclose : 5000, position: "top-right", type:"st-error" });
			}
		
	});
	
</script>