<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
      foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>         
<?php }
    
}?>
<div class="row-fluid">
	<h1 class="heading">Criar Envio - Pedido #<?= $this->data->getOrderCod();?></h1>	
	<input id="orderId" type="hidden" value="<?= $this->orderId;?>"/>
</div>