<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title><?php echo $this -> title; ?></title>        
      <?php echo $this -> render('admin-necessary.phtml'); ?>   
       	
	
	
    </head>
	
	<body class="loading">
	     
		<div id="maincontainer" class="clearfix">
			
            <!-- Header -->
            <?php echo $this->render('admin-header.phtml'); ?>
            
            <!-- Main-Content -->
            <div id="contentwrapper">
            	<div class="main_content" role="main">
            		
                    <?php echo $this->layout()->content; ?>

            	</div>
            </div>
            
            <!-- Sidebar -->
            <div>
                <?php echo $this->render('admin-sidebar.phtml'); ?>
            </div>
        <div class="wait">
            <h1></h1>
        </div>
		</div>
		
	</body>
   <script type="text/javascript">
       $( document ).ready(function() {
            $('.wait h1').html("");   
            $('body').removeClass("loading");     
       });
   </script>
</html>

