<!-- sidebar -->
            <a href="javascript:void(0)" class="sidebar_switch on_switch ttip_r" title="Hide Sidebar">Sidebar switch</a>
            <div class="sidebar">
				<div class="antiScroll">
					<div class="antiscroll-inner">
						<div class="antiscroll-content">
							<div class="sidebar_inner">
								<form action="index.php?uid=1&amp;page=search_page" class="input-append" method="post" >
									<input autocomplete="off" name="query" class="search_query input-medium" size="16" type="text" placeholder="Search..." /><button type="submit" class="btn"><i class="icon-search"></i></button>
								</form>
								<div id="side_accordion" class="accordion">
									<div class="accordion-group">
										<div class="accordion-heading">
											<a href="#collapseOne" data-parent="#side_accordion" data-toggle="collapse" class="accordion-toggle">
												Clientes
											</a>
										</div>
										<div class="accordion-body collapse" id="collapseOne">
											<div class="accordion-inner">
												<ul class="nav nav-list">
													<li><a href="/admin238/customer/add">Adicionar Novo</a></li>
													<li><a href="/admin238/customer">Listar Clientes</a></li>
												</ul>
												<ul class="nav nav-list">
													<li class="nav-header">Relatórios</li>
													<li><a href="#">Melhores Clientes</a></li>
													<li><a href="#">Clientes Novos</a></li>													
												</ul>
											</div>
										</div>
									</div>
									<div class="accordion-group">
										<div class="accordion-heading">
											<a href="#collapseTwo" data-parent="#side_accordion" data-toggle="collapse" class="accordion-toggle">
												Categorias & Produtos
											</a>
										</div>
										<div class="accordion-body collapse" id="collapseTwo">
											<div class="accordion-inner">
												<ul class="nav nav-list">
													<li class="nav-header">Categorias</li>
													<li><a href="/admin238/category/add">Adicionar Nova</a></li>
													<li><a href="/admin238/category">Listar Categorias</a></li>
												</ul>
												<ul class="nav nav-list">
													<li class="nav-header">Produtos</li>
													<li><a href="/admin238/product/add">Adicionar Novo</a></li>
													<li><a href="/admin238/product">Listar Produtos</a></li>
												</ul>
												<ul class="nav nav-list">
													<li class="nav-header">Estoque</li>
													<li><a href="/admin238/product/stock">Gerenciar Estoque</a></li>
													<li><a href="/admin238/product">Relatório</a></li>
													<li><a href="/admin238/product">Auditoria</a></li>
												</ul>												
												<ul class="nav nav-list">
													<li class="nav-header">Relatórios</li>													
													<li><a href="#">Mais Vendidos</a></li>
													<li><a href="#">Mais Visualizados</a></li>
												</ul>
											</div>
										</div>
									</div>
									<div class="accordion-group">
										<div class="accordion-heading">
											<a href="#collapseThree" data-parent="#side_accordion" data-toggle="collapse" class="accordion-toggle">
												Pedidos & Entregas
											</a>
										</div>
										<div class="accordion-body collapse" id="collapseThree">
											<div class="accordion-inner">
												<ul class="nav nav-list">
													<li class="nav-header">Vendas</li>
													<li><a href="/admin238/manage-orders">Gerenciar Pedidos</a></li>
													<li><a href="#">Criar Pedido</a></li>													
												</ul>
												<ul class="nav nav-list">
													<li class="nav-header">Faturas</li>
													<li><a href="#">Gerenciar Faturas</a></li>
													<li><a href="#">Criar Faturas</a></li>													
												</ul>
												<ul class="nav nav-list">
													<li class="nav-header">Entregas</li>
													<li><a href="#">Gerenciar Entregas</a></li>
													<li><a href="#">Criar Entrega</a></li>													
												</ul>
												<ul class="nav nav-list">
                                                    <li class="nav-header">Relatórios</li>
                                                    <li><a href="#">Vendas</a></li>                                                    
                                                    <li><a href="#">Carrinhos Abandonados</a></li>                                
                                                </ul>												
											</div>
										</div>
									</div>
									
									<div class="accordion-group">
										<div class="accordion-heading">
											<a href="#collapseFour" data-parent="#side_accordion" data-toggle="collapse" class="accordion-toggle">
												Promoções
											</a>
										</div>
										<div class="accordion-body collapse" id="collapseFour">
											<div class="accordion-inner">
												<ul class="nav nav-list">
													<li class="nav-header">Promoções</li>
													<li><a href="#">Gerenciar Promoções</a></li>
													<li><a href="#">Tipos de Promoção</a></li>
													<li><a href="#">Criar Promoção</a></li>
													<li><a href="#">Relatórios</a></li>
												</ul>
												<ul class="nav nav-list">
													<li class="nav-header">Cupons</li>
													<li><a href="#">Gerenciar Cupons</a></li>
													<li><a href="#">Criar Cupom</a></li>
													<li><a href="#">Relatórios</a></li>
												</ul>
												
											</div>
										</div>
									</div>
									
									<div class="accordion-group">
                                        <div class="accordion-heading">
                                            <a href="#collapseFive" data-parent="#side_accordion" data-toggle="collapse" class="accordion-toggle">
                                                Financeiro
                                            </a>
                                        </div>
                                        <div class="accordion-body collapse" id="collapseFive">
                                            <div class="accordion-inner">
                                                <ul class="nav nav-list">
                                                    <li class="nav-header">Contas a Pagar</li>
                                                    <li><a href="#">Contas a Pagar</a></li>
                                                    <li><a href="#">Cadastro de Fornecedores</a></li>                                                   
                                                </ul>
                                                <ul class="nav nav-list">
                                                    <li class="nav-header">Contas a Receber</li>
                                                    <li><a href="#">Contas a Receber</a></li>                                                                                                      
                                                </ul>
                                                <ul class="nav nav-list">
                                                    <li class="nav-header">Relatórios</li>
                                                    <li><a href="#">Faturamento</a></li>
                                                    <li><a href="#">Fluxo de Caixa</a></li>                                                  
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="accordion-group">
                                        <div class="accordion-heading">
                                            <a href="#collapseSix" data-parent="#side_accordion" data-toggle="collapse" class="accordion-toggle">
                                                RH
                                            </a>
                                        </div>
                                        <div class="accordion-body collapse" id="collapseSix">
                                            <div class="accordion-inner">
                                                <ul class="nav nav-list">
                                                    <li class="nav-header">Cadastro</li>
                                                    <li><a href="#">Funcionarios</a></li>
                                                    <li><a href="#">Cargos</a></li>
                                                    <li><a href="#">Comissões</a></li>
                                                    <li><a href="#">Salários</a></li>                    
                                                </ul>
                                                <ul class="nav nav-list">
                                                    <li class="nav-header">Relatórios</li>
                                                    <li><a href="#">Salários</a></li>                                                                                                     
                                                </ul>
                                               
                                            </div>
                                        </div>
                                    </div>
                                    
                                     <div class="accordion-group">
                                        <div class="accordion-heading">
                                            <a href="#collapseSeven" data-parent="#side_accordion" data-toggle="collapse" class="accordion-toggle">
                                                Sistema
                                            </a>
                                        </div>
                                        <div class="accordion-body collapse" id="collapseSeven">
                                            <div class="accordion-inner">
                                                <ul class="nav nav-list">
                                                    <li class="nav-header">Loja</li>
                                                    <li><a href="#">Dados Cadastrais</a></li>
                                                    <li><a href="#">Configuração de Email</a></li>                                                                      
                                                </ul>
                                                <ul class="nav nav-list">
                                                    <li class="nav-header">Produtos</li>
                                                    <li><a href="#">Configurações de Produto</a></li>                                                                                                     
                                                </ul>
                                                <ul class="nav nav-list">
                                                    <li class="nav-header">Pagamento</li>
                                                    <li><a href="#">Formas de Pagamento</a></li>                                                                                                     
                                                </ul>
                                                <ul class="nav nav-list">
                                                    <li class="nav-header">Entrega</li>
                                                    <li><a href="#">Formas de Entrega</a></li>                                                                                                     
                                                </ul>
                                                
                                               
                                            </div>
                                        </div>
                                    </div>
									


								</div>
							</div>
						</div>
					</div>
				</div>
			</div>