        <!-- Bootstrap framework -->
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/bootstrap/css/bootstrap.min.css" />
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/bootstrap/css/bootstrap-responsive.min.css" />
        <!-- tooltips-->
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/lib/qtip2/jquery.qtip.min.css" />
        
        <!-- gebo color theme-->
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/css/custom.css" id="link_theme" />
        <!-- main styles -->
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/css/style.css" />
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/css/main.css" />
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/lib/sticky/sticky.css" />    
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/img/splashy/splashy.css" />
             
        
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.min.js"></script>
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery-migrate.min.js"></script>
            <!-- smart resize event -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.debouncedresize.min.js"></script>
            <!-- hidden elements width/height -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.actual.min.js"></script>
            <!-- js cookie plugin -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery_cookie.min.js"></script>
            <!-- main bootstrap js -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/bootstrap/js/bootstrap.min.js"></script>
             <!-- bootstrap plugins -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/bootstrap.plugins.min.js"></script>
            <!-- tooltips -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/qtip2/jquery.qtip.min.js"></script>
            
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/sticky/sticky.min.js"></script>
            <!-- fix for ios orientation change -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/ios-orientationchange-fix.js"></script>
            <!-- scrollbar -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/antiscroll/antiscroll.js"></script>
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/antiscroll/jquery-mousewheel.js"></script>
            <!-- mobile nav -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/selectNav.js"></script>
            <!-- common functions -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/gebo_common.js"></script>
            
            <!-- mask -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.mask.js"></script>
            
            <!-- colorbox -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/colorbox/jquery.colorbox.min.js"></script>
            <!-- datatable -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/datatables/jquery.dataTables.min.js"></script>
            <!-- additional sorting for datatables -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/datatables/jquery.dataTables.sorting.js"></script>
            <!-- datatables bootstrap integration -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/datatables/jquery.dataTables.bootstrap.min.js"></script>
            <!-- tables functions -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/gebo_tables.js"></script>
            
            <!-- Includes JS Especificos da View -->
            <?php
                if ($this->jQueryValidation == true){ ?>
                    <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/validation/jquery.validate.min.js"></script>
            <?php        
                }
            ?>
    
            <script>
                $(document).ready(function() {
                    //* show all elements & remove preloader
                    setTimeout('$("html").removeClass("js")',1000);
                });
            </script>