        <!-- Bootstrap framework -->
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/bootstrap/css/bootstrap.min.css" />
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/bootstrap/css/bootstrap-responsive.min.css" />
        <!-- tooltips-->
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/lib/qtip2/jquery.qtip.min.css" />
        
        <!-- gebo color theme-->
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/css/custom.css" id="link_theme" />
        <!-- main styles -->
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/css/style.css" />
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/css/main.css" />
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/lib/sticky/sticky.css" />    
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/img/splashy/splashy.css" />
            
          <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/lib/datatables/extras/TableTools/media/css/TableTools.css"> 
            
            <?php if ($this->categoryPage == true || $this->productPage == true){?>
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/lib/dynatree/src/skin/ui.dynatree.css" />
            <?php }?>
            
            <?php if ($this->productPage == true){?>            
            <link rel="stylesheet" href="http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/css/fileupload/jquery.fileupload.css" />
            
            <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/admin/css/fileupload/jquery.fileupload-ui.css" />
            
           <?php }?>
           
        
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.min.js"></script>
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery-migrate.min.js"></script>
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/jquery-ui/jquery-ui-1.10.0.custom.min.js"></script>
                                    
            <!-- smart resize event -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.debouncedresize.min.js"></script>
            <!-- hidden elements width/height -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.actual.min.js"></script>
            <!-- js cookie plugin -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery_cookie.min.js"></script>
            <!-- main bootstrap js -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/bootstrap/js/bootstrap.min.js"></script>
             <!-- bootstrap plugins -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/bootstrap.plugins.min.js"></script>
            <!-- tooltips -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/qtip2/jquery.qtip.min.js"></script>
            
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/sticky/sticky.min.js"></script>
            <!-- fix for ios orientation change -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/ios-orientationchange-fix.js"></script>
            <!-- scrollbar -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/antiscroll/antiscroll.js"></script>
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/antiscroll/jquery-mousewheel.js"></script>
           <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/UItoTop/jquery.ui.totop.min.js"></script> 
            
            <!-- mobile nav -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/selectNav.js"></script>
            <!-- common functions -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/gebo_common.js"></script>
            
            <!-- mask -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.mask.js"></script>
            
            <!-- colorbox -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/colorbox/jquery.colorbox.min.js"></script>
            <!-- datatable -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/datatables/jquery.dataTables.min.js"></script>
            <!-- additional sorting for datatables -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/datatables/jquery.dataTables.sorting.js"></script>
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/datatables/extras/TableTools/media/js/TableTools.min.js"></script>
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/datatables/extras/TableTools/media/js/ZeroClipboard.js"></script>
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/datatables/extras/Scroller/media/js/dataTables.scroller.min.js"></script>
            <!-- datatables bootstrap integration -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/datatables/jquery.dataTables.bootstrap.min.js"></script>
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/gebo_datatables.js"></script>
            <!-- tables functions -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/gebo_tables.js"></script>
            <!-- jquery validate -->
            <script src="<?php echo $this->baseUrl();?>/assets/admin/lib/validation/jquery.validate.min.js"></script>
           
            <?php if ($this->categoryPage == true || $this->productPage == true){?>
            	<script src="<?php echo $this->baseUrl();?>/assets/admin/lib/dynatree/dist/jquery.dynatree.min.js"></script>
            <?php }?>
            
            <?php if ($this->productPage == true){?>
            <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.ui.widget.js"></script>
            <!-- The Templates plugin is included to render the upload/download listings -->
            <script src="http://blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
            <!-- The Load Image plugin is included for the preview images and image resizing functionality -->
            <script src="http://blueimp.github.io/JavaScript-Load-Image/js/load-image.min.js"></script>
            <!-- The Canvas to Blob plugin is included for image resizing functionality -->
            <script src="http://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
            <script src="http://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
            	<script src="<?php echo $this->baseUrl();?>/assets/admin/lib/tinymce/tinymce.min.js"></script>
                <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.iframe-transport.js"></script>
                <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.fileupload.js"></script>
                <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.fileupload-process.js"></script>
                <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.fileupload-image.js"></script>
                <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.fileupload-audio.js"></script>
                <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.fileupload-video.js"></script>
                <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.fileupload-validate.js"></script>
                <script src="<?php echo $this->baseUrl();?>/assets/admin/js/jquery.fileupload-ui.js"></script>
                <script src="<?php echo $this->baseUrl();?>/assets/admin/js/main.js"></script>
            <?php }?>
           