<!-- header -->
            <header>
                <div class="navbar navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container-fluid">
                            <a class="brand" href="/admin"><i class="icon-home icon-white"></i>myStore</a>
                            <ul class="nav user_menu pull-right">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->name; ?><b class="caret"></b></a>
                                    <ul class="dropdown-menu">
										<li><a href="#">Action</a></li>
										<li><a href="#">Another Action</a></li>
										<li class="divider"></li>
										<li><a href="/admin/logout">Sair</a></li>
                                    </ul>
                                </li>
                            </ul>
							<a data-target=".nav-collapse" data-toggle="collapse" class="btn_menu">
								<span class="icon-align-justify icon-white"></span>
							</a>
                            <nav>
                                <div class="nav-collapse">
                                    <ul class="nav">
                                        <!--  
										<li class="dropdown">
                                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Páginas<b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="#">Adicionar</a></li>
                                                <li><a href="#">Editar</a></li>
                                            </ul>
                                        </li>-->
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </header>