<!-- sidebar -->
            <a href="javascript:void(0)" class="sidebar_switch on_switch ttip_r" title="Hide Sidebar">Sidebar switch</a>
            <div class="sidebar">
				<div class="antiScroll">
					<div class="antiscroll-inner">
						<div class="antiscroll-content">
							<div class="sidebar_inner">
								<form action="index.php?uid=1&amp;page=search_page" class="input-append" method="post" >
									<input autocomplete="off" name="query" class="search_query input-medium" size="16" type="text" placeholder="Search..." /><button type="submit" class="btn"><i class="icon-search"></i></button>
								</form>
								<div id="side_accordion" class="accordion">
									<div class="accordion-group">
										<div class="accordion-heading">
											<a href="#collapseOne" data-parent="#side_accordion" data-toggle="collapse" class="accordion-toggle">
												Clientes
											</a>
										</div>
										<div class="accordion-body collapse" id="collapseOne">
											<div class="accordion-inner">
												<ul class="nav nav-list">
													<li><a href="#">Gerenciar Clientes</a></li>
													<li><a href="#">Adicionar Novo</a></li>
												</ul>
												<ul class="nav nav-list">
													<li class="nav-header">Relatórios</li>
													<li><a href="#">Melhores Clientes</a></li>
													<li><a href="#">Clientes Novos</a></li>
													<li><a href="#">Carrinhos Abandonados</a></li>
												</ul>
											</div>
										</div>
									</div>
									<div class="accordion-group">
										<div class="accordion-heading">
											<a href="#collapseTwo" data-parent="#side_accordion" data-toggle="collapse" class="accordion-toggle">
												Categorias & Produtos
											</a>
										</div>
										<div class="accordion-body collapse" id="collapseTwo">
											<div class="accordion-inner">
												<ul class="nav nav-list">
													<li class="nav-header">Produtos</li>
													<li><a href="#">Adicionar Novo</a></li>
													<li><a href="#">Listar Produtos</a></li>
												</ul>
												<ul class="nav nav-list">
													<li class="nav-header">Categorias</li>
													<li><a href="#">Adicionar Nova</a></li>
													<li><a href="#">Listar Categorias</a></li>
												</ul>
												<ul class="nav nav-list">
													<li class="nav-header">Relatórios</li>
													<li><a href="#">Mais Vendidos</a></li>
													<li><a href="#">Mais Visualizados</a></li>
												</ul>
											</div>
										</div>
									</div>
									<div class="accordion-group">
										<div class="accordion-heading">
											<a href="#collapseThree" data-parent="#side_accordion" data-toggle="collapse" class="accordion-toggle">
												Pedidos & Entregas
											</a>
										</div>
										<div class="accordion-body collapse" id="collapseThree">
											<div class="accordion-inner">
												<ul class="nav nav-list">
													<li class="nav-header">Pedidos</li>
													<li><a href="#">Gerenciar Pedidos</a></li>
													<li><a href="#">Criar Pedido</a></li>													
												</ul>
												<ul class="nav nav-list">
													<li class="nav-header">Faturas</li>
													<li><a href="#">Gerenciar Faturas</a></li>
													<li><a href="#">Criar Faturas</a></li>													
												</ul>
												<ul class="nav nav-list">
													<li class="nav-header">Entregas</li>
													<li><a href="#">Gerenciar Entregas</a></li>
													<li><a href="#">Criar Entrega</a></li>													
												</ul>
											</div>
										</div>
									</div>
									
									<div class="accordion-group">
										<div class="accordion-heading">
											<a href="#collapseFour" data-parent="#side_accordion" data-toggle="collapse" class="accordion-toggle">
												Promoções
											</a>
										</div>
										<div class="accordion-body collapse" id="collapseFour">
											<div class="accordion-inner">
												<ul class="nav nav-list">
													<li class="nav-header">Promoções</li>
													<li><a href="#">Gerenciar Promoções</a></li>
													<li><a href="#">Tipos de Promoção</a></li>
													<li><a href="#">Criar Promoção</a></li>
													<li><a href="#">Relatórios</a></li>
												</ul>
												<ul class="nav nav-list">
													<li class="nav-header">Cupons</li>
													<li><a href="#">Gerenciar Cupons</a></li>
													<li><a href="#">Criar Cupom</a></li>
													<li><a href="#">Relatórios</a></li>
												</ul>
												
											</div>
										</div>
									</div>
									


								</div>
							</div>
						</div>
					</div>
				</div>
			</div>