<!-- header -->
            <header>
                <div class="navbar navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container-fluid">
                            <a class="brand" href="/admin"><i class="icon-home icon-white"></i>myStore</a>
                            <ul class="nav user_menu pull-right">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $this->username; ?><b class="caret"></b></a>
                                    <ul class="dropdown-menu">
										<li><a href="#">Action</a></li>
										<li><a href="#">Another Action</a></li>
										<li class="divider"></li>
										<li><a href="/admin238/index/logout">Sair</a></li>
                                    </ul>
                                </li>
                            </ul>
							<a data-target=".nav-collapse" data-toggle="collapse" class="btn_menu">
								<span class="icon-align-justify icon-white"></span>
							</a>
                            <nav>
                                <div class="nav-collapse">
                                    <ul class="nav">                                        
										<li>
                                            <a href="/admin238">Painel</a>                                           
                                        </li>
                                        <li class="dropdown">
                                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Vendas<b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="/admin238/manage-orders">Gerenciar Pedidos</a></li>
                                                <li><a href="/admin238/manage-orders/list-shippings">Gerenciar Envios</a></li>
                                                <li><a href="/admin238/manage-orders/mass-shipping">Enviar em Lote</a></li>
                                            </ul>                                            
                                        </li>
                                        <li class="dropdown">
                                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Produtos<b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="/admin238/product">Gerenciar Produtos</a></li>
                                                <li><a href="/admin238/category">Gerenciar Categorias</a></li>
                                            </ul>                                            
                                        </li>
                                        <li class="dropdown">
                                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Clientes<b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="/admin238/customer">Gerenciar Clientes</a></li>
                                            </ul>                                            
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </header>