<div class="navbar navbar-inverse navbar-fixed-top navmain" role="navigation">   
        <div class="col-md-3 col-sm-3 center-height">log</div>
        <div class="col-xs-2 col-md-1 col-sm-1 center-height">
            <span class="glyphicon glyphicon-chevron-right">Ajuda</span>
        </div>
        <div class="col-xs-10 col-sm-4 col-md-5 center-height">
            <div class="col-xs-8 col-md-8 no-padding">
                <input type="text" class="form-control" placeholder="Que tipo de capa você procura?"/>
            </div>
            <div class="col-xs-4 col-md-4 no-padding">
                <button class="btn btn-success">Buscar</button>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-3 center-height">
            <div class="col-xs-8">
                Entre ou Cadastre-se
            </div>
            <div class="col-xs-4">
                <a class="cart-link">
                    <span class="cart-icon"></span>
                </a>
            </div>
        </div>
</div>