 <!-- Bootstrap framework -->
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/front/theme1/css/bootstrap.min.css" media="screen">
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/front/theme1/css/jquery-ui-1.10.1.min.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/front/theme1/css/customize.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/front/theme1/css/font-awesome.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/front/theme1/css/style.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/front/theme1/css/flexslider.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/front/theme1/js/fancybox/jquery.fancybox.css" />
<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
		<link rel="stylesheet" href="css/font-awesome-ie7.css">
	<![endif]-->
