<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>AppleMax</title>        
        <?php echo $this->render('front-styles.phtml'); ?>	
    </head>
    <body>
    	<?php echo $this->render('front-header.phtml'); ?>
    	<footer>
    	<?php echo $this->render('front-footer.phtml'); ?>
    	</footer>
    </body>
</html>