 </div>
 
 
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
 <script>
 	$(function() {
		cbpHorizontalMenu.init();
 	});
 </script>
 
 <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js"></script>
 
 <script src="<?php echo $this->baseUrl();?>/assets/front/js/bootstrap.js"></script>
 
 
	<!-- jQuery.Cookie -->
	<script src="<?php echo $this->baseUrl();?>/assets/front/theme1/js/jquery.cookie.js"></script>
	<!-- bootstrap -->
    <script src="<?php echo $this->baseUrl();?>/assets/front/theme1/js/bootstrap.min.js"></script>
    <!-- flexslider -->
    <script src="<?php echo $this->baseUrl();?>/assets/front/theme1/js/jquery.flexslider-min.js"></script>
    <!-- cycle2 -->
    <script src="<?php echo $this->baseUrl();?>/assets/front/theme1/js/jquery.cycle2.min.js"></script>
    <script src="<?php echo $this->baseUrl();?>/assets/front/theme1/js/jquery.cycle2.carousel.min.js"></script>
    <!-- tweets -->
    <script src="<?php echo $this->baseUrl();?>/assets/front/theme1/js/jquery.tweet.js"></script>
    <!-- placeholder -->
    <script src="<?php echo $this->baseUrl();?>/assets/front/theme1/js/jquery.placeholder.min.html"></script>
    <!-- fancybox -->
    <script src="<?php echo $this->baseUrl();?>/assets/front/theme1/js/fancybox/jquery.fancybox.js"></script>
    <!-- custom function-->
    <script src="<?php echo $this->baseUrl();?>/assets/front/theme1/js/custom.js"></script>
    
    <script src="<?php echo $this->baseUrl();?>/assets/front/theme1/js/cbpHorizontalMenu.min.js"></script>
    
  