<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
    foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>
<div class="row-fluid">
    <div class="span12">
        <h1 class="heading">Categorias</h1>
        <div class="row-fluid">
        	<button class="btn addCategory">Adicionar Nova</button>       
        </div>
        <div class="row-fluid">
			<table class="table table-bordered table-condensed categories" data-provides="rowlink">
				<tbody>
					<?php foreach($this->categories as $category){ ?>
					<tr class="primary">
						<td style="display:none"><input type="hidden" class="categoryid" value="<?= $category['id']?>"/></td>
						<td class="primary"><a href="/admin238/category/edit/id/<?php echo $category['id']?>"><?php echo $category['name'];?></a></td>
						<td colspan="2"></td>						
						<td><button class="btn remove">Excluir</button></td>
					</tr>
					<?php if(count($category) > 2){?>
						<?php foreach ($category as $sub1){ 
							if (is_array($sub1)){?>
					<tr class="secondary">
						<td style="display:none"><input type="hidden" class="categoryid" value="<?= $sub1['id']?>"/></td>
						<td></td>
						<td class="secondary"><a href="/admin238/category/edit/id/<?php echo $sub1['id']?>"><?php echo $sub1['name']?></a></td>
						<td></td>
						<td><button class="btn remove">Excluir</button></td>
					</tr>
								<?php if(count($sub1 > 2)){?>
								<?php foreach($sub1 as $sub2){
									      if (is_array($sub2)){?>
											<tr class="tertiary">
												<td style="display:none"><input type="hidden" class="categoryid" value="<?= $sub2['id']?>"/></td>
												<td colspan="2"></td>						
												<td class="tertiary"><a href="/admin238/category/edit/id/<?php echo $sub2['id']?>"><?php echo $sub2['name']?></a></td>
												<td><button class="btn remove">Excluir</button></td>
											</tr>	
							    <?php   
                                        }
							          }}}}}?>
					<?php }?>
				</tbody>
			</table>           
	   </div>       
                               

    </div>
    <div class="span12">
       
    </div>
</div>

<script type="text/javascript">

	$('button.addCategory').on('click',function(){
		window.location.replace('/admin238/category/add');
	});

	$('button.remove').on('click',function(){
		var categoryid = $(this).parent().parent().find('input.categoryid').val();
		window.location.replace('/admin238/category/remove?categoryid='+categoryid);
		return false;
	});

</script>
