<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
    foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>         
<?php }
    
}?>
<div class="row-fluid">	
	    
		<h1 class="heading">Novo Produto - ID: <?= $this->productId; ?></h1>
		<div id="errordiv"></div>
		<div id="gap_form">
			<div class="tabbable tabbable-bordered">
			
				<ul class="nav nav-tabs">
				    <button onclick="sendProductForm()" class="btn btn-gebo">Salvar</button>
					<li class="active"><a data-toggle="tab" href="#tab_br1">Dados Gerais</a></li>
					<li class=""><a data-toggle="tab" href="#tab_br2">Preço</a></li>
					<li class=""><a data-toggle="tab" href="#tab_br3">Estoque</a></li>
					<li class=""><a data-toggle="tab" href="#tab_br4">Imagens</a></li>
					<li class=""><a data-toggle="tab" href="#tab_br5">Meta Tags</a></li>
				</ul>					
				<div class="tab-content">
					<div id="tab_br1" class="tab-pane active">
						<h4 class="heading">Dados Gerais</h4>						
						<?php echo $this->content->render('general.phtml');?>
					</div>
					<div id="tab_br2" class="tab-pane">
						<h4 class="heading">Informações de Preço</h4>
						<?php echo $this->content->render('price.phtml');?>
					</div>
					<div id="tab_br3" class="tab-pane">
						<h4 class="heading">Gerenciar Estoque</h4>
						<?php echo $this->content->render('stock.phtml');?>
					</div>
					<div id="tab_br4" class="tab-pane">
						<h4 class="heading">Gerenciar Imagens</h4>
						<?php echo $this->content->render('images.phtml');?>
					</div>
					<div id="tab_br5" class="tab-pane">
						<h4 class="heading">Meta Tags</h4>
						<?php// echo $this->content->render('metatags.phtml');?>
					</div>
				</div>
			</div>
		</div>		
	
</div>

<script type="text/javascript">   

    function sendProductForm(){
            $('form#fileupload').remove();
            $('#errordiv').empty();
            $('#productForm').validate({
                ignore:"",
                rules:{
                    name:{
                        required:true
                    },
                    sku:{
                        required:true
                    },
                    desc1:{
                        required:true
                    },
                    normal_price:{
                        required:true                       
                    },
                    weight:{
                        number:true
                    }
                },
                messages:{
                    name:{
                        required: "O campo nome é obrigatorio."               
                    },
                    sku:{
                        required: "O campo sku é obrigatorio."               
                    },
                    desc1:{
                        required: "O campo descrição resumida é obrigatorio."               
                    },
                    normal_price:{
                        required: "O campo preço é obrigatorio."  
                    },
                    weight:{
                        number: "O peso deve ser um número inteiro ou decimal"
                    }
                }
            });
    }
    
    jQuery('.numbers').keyup(function () { 
        this.value = this.value.replace(/[^0-9\.]/g,'');
    });   
        
    $(document).ready(function() {
        
        $('#gap_form').wrap('<form id="productForm" action="/admin238/product/add" method="post" ></form>');
        
        $('.dateme').mask('00/00/0000');
        $('.moneyme').mask('000.000.000.000.000,00', {
            reverse : true
        });
        
        $('a.price-range-add').click(function(){
            var from = $('input[name="qty_from"]').val();
            var to = $('input[name="qty_to"]').val();
            var price = $('input[name="price_range"]').val();
            if(from && to && price){
                var lastFrom = $('tbody#price-range-table tr:last-child td input.from').val();
                var lastTo = $('tbody#price-range-table tr:last-child td input.to').val();
                if(lastTo != undefined){
                    if (parseInt(from) > parseInt(lastTo)){
                        if(parseInt(from) > parseInt(to) || parseInt(from) == parseInt(to)){                    
                            alert('Existe um conflito desses valores com uma faixa já existente');
                        }else{                    
                            $('tbody#price-range-table').append('<tr><td><input type="hidden" name="from[]" class="from" value="' + from  + '"/>' + from + '</td><td><input type="hidden" name="to[]" class="to" value="' + to  + '"/>' + to + '</td><td><input type="hidden" name="price[]" class="price" value="' + price  + '"/>' + price + '</td><td><a class="price-range-remove" > <i class="splashy-remove"></i></a></td></tr>');
                        }
                    }else{
                        alert('Valor "De" precisa ser maior do que o valor "Até" da última faixa');
                    }
                }else{                    
                    $('tbody#price-range-table').append('<tr><td><input type="hidden" name="from[]" class="from" value="' + from  + '"/>' + from + '</td><td><input type="hidden" name="to[]" class="to" value="' + to  + '"/>' + to + '</td><td><input type="hidden" name="price[]" class="price" value="' + price  + '"/>' + price + '</td><td><a class="price-range-remove" > <i class="splashy-remove"></i></a></td></tr>');
                }
               
            }else{
                alert('Preencha os campos de faixa de preço!');
            }
        });       

        $('button[name="upload-all"]').click(function(event){
        	
			name = $('p.name a').html();
			productid = <?= $this->productId; ?>;
			if($('input[name=order]').val() != ''){
				order = $('input[name=order]').val();
			}else{
				order = 1;
			}
					
			$.ajax({
        		url: "/admin238/product/add-image",
        		type:"GET",
        		data:{productid:productid, name:name, order:order},
        		contentType: "application/json; charset=utf-8",
        		dataType:"json",
        		success: function (data) { },
                error: function(request,error){
                	 console.log(arguments);
                	 alert ( " Can't do because: " + error );
                }
        	});
        });
    });
        
        $('a.price-range-remove').click(function(){ 
                alert('oi');                  
            $(this).parent().parent().remove();
        });
    
</script>