<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
      foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>         
<?php }
    
}?>
<div class="row-fluid">
	<div class="span12">
<h1 class="heading">Produtos<button class="btn add-new"><a href="/admin238/product/add">Criar Novo</a></button></h1>
	<div class="row-fluid">
		<div class="span2">
			<div class="dt_actions">
				<div class="btn-group">
					<button class="btn dropdown-toggle" data-toggle="dropdown">Ações em Massa <span class="caret"></span></button>
						<ul class="dropdown-menu">
							<li><a href="javascript:void(0)" class="select_rows">Selecionar Tudo</a></li>
							<li><a href="javascript:void(0)" class="deselect_rows">Deselecionar Tudo</a></li>
							<li><a data-tableid="dt_gal" class="delete_rows_dt" href="#"><i class="icon-trash"></i> Remover</a></li>
	                    	<li><a href="javascript:void(0)" class="enable_rows"><i class="splashy-gem_okay"></i>Habilitar</a></li>
	                    	<li><a href="javascript:void(0)" class="disable_rows"><i class="splashy-gem_remove"></i>Desabilitar</a></li>
	                	</ul>
				</div>			
			</div>		
					
		</div>
		<div class="span1">		
			<select name="maxPages" class="span12">
				<option value="2">1</option>
				<option value="3">3</option>
				<option value="5">5</option>
			</select>
		</div>		
	</div>
		<div class="row-fluid">
		<?php echo $this->pagination;?>
		</div>
		<table class="table table-striped table-bordered dTableR product-results" >
			<thead>
				<tr>
					<th></th>
					<th>ID</th>
					<th>Imagem</th>
					<th class="span4">Nome</th>
					<th class="span2">SKU</th>
					<th class="span2">Preço</th>
					<th class="span1">Estoque</th>
					<th class="span3">Status</th>
					<th>Ações</th>
				</tr>
			</thead>
			<tbody>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td><input type="text" name="search_name" value="" class="span12"/></td>
						<td><input type="text" name="search_sku" value="" class="span12"/></td>
						<td>
							<input type="text" name="search_price_from" value="" class="span12" placeholder="De"/>
						    <input type="text" name="search_price_to" value="" class="span12" placeholder="Até"/>
						</td>
						<td>
							<input type="text" name="search_stock_from" value="" class="span12" placeholder="De"/>
							<input type="text" name="search_stock_to" value="" class="span12" placeholder="Até"/>
						</td>
						<td>
						    <select name="search_status" class="span12">
						        <option value="1">Habilitado</option>
						        <option value="0">Desabilitado</option>
						    </select>
						</td>
						<td><button class="btn search">Buscar</button></td>
					</tr>
				<?php foreach($this->products as $product){ ?>
						
					<tr class="result">
		    			<td><input type="checkbox" name="row_sel" class="row_sel" value="<?= $product->getId();?>"/></td>
		    			<td><?php echo $product->getId();?></td>
		    			<td style="width: 60px"><a href="<?php if ($product->getImages()[0]){echo '/images/catalog/' . $product->getId() . '/' . $product->getImages()[0]->getName();};?>"
		    				title="" class="cbox_single thumbnail"> <img alt="" src="<?php if ($product->getImages()[0]){echo '/images/catalog/' . $product->getId() . '/thumbnail/' . $product->getImages()[0]->getName();};?>" style="height: 50px; width: 50px">
		    			</a>
		    			</td>
		    			<td><?php echo $product->getName();?></td>
		    			<td><?php echo $product->getSku();?></td>
		    			<td><?php if($product->getPrice()){ echo 'R$' . $product->getPrice();}?></td>
		    			<td><?php if($product->getCurrentQty()){echo $product->getCurrentQty();}?></td>			
		    			<td><?php if($product->getStatus() == '1'){echo '<a href="/admin238/product/disable?product_id='.$product->getId().'"><i class="splashy-gem_okay"></i>Ativo';}else{ echo '<a href="/admin238/product/enable?product_id='.$product->getId().'"><i class="splashy-gem_remove"></i>Desabilitado</a>';}?></td>
		    			<td><a href="<?= '/admin238/product/edit?product_id=' . $product->getId();?>" class="sepV_a" title="Edit"><i class="icon-pencil"></i>
		    				</a> <a href="#" title="Delete"><i class="icon-trash"></i> </a>
		    			</td>
				    </tr>
				    
				<?php }?>
				
			</tbody>
		</table>
		<?php echo $this->pagination;?>
</div>
</div>
</div>

<script>
$('.add-new').on('click',function(event){
	confirm('Deseja criar um novo produto?');
	return true;
});
$('.select_rows').on('click',function(event){
	$('.row_sel').prop('checked',true);
});
$('.deselect_rows').on('click',function(event){
	$('.row_sel').prop('checked',false);
});

$('button.search').on('click',function(){
    
    $('.wait h1').html('Estou procurando...');
    $('body').addClass('loading');
    
    var name = $('input[name="search_name"]').val();
    var sku = $('input[name="search_sku"]').val();
    var status = $('select[name="search_status"]').val();
    var stockFrom =  $('input[name="search_stock_from"]').val();
    var stockTo =  $('input[name="search_stock_to"]').val();
    var priceFrom =  $('input[name="search_price_from"]').val();
    var priceTo =  $('input[name="search_price_to"]').val();

   
    $.ajax({
        url: "/admin238/product/filter",
        type:"GET",
        data:{name:name, sku:sku, status:status, priceFrom:priceFrom, priceTo:priceTo, stockFrom:stockFrom, stockTo:stockTo},
        contentType: "application/json; charset=utf-8",
        dataType:"json",
        success: function (data) { 
           $('body').removeClass('loading');
           $('tr.result').remove();
           $('table.product-results tbody').append(data);          
        },
        error: function(request,error){
            $('body').removeClass('loading');          
            console.log(arguments);
            $.sticky(error, {autoclose : 5000, position: "top-right", type:"st-error" });
        }
    });
});


</script>