<div class="row-fluid">
	<div class="span12">
<h1 class="heading">Produtos</h1>
<table class="table table-bordered table-striped table_vam" >
	<thead>
		<tr>
			<th class="table_checkbox"><input type="checkbox" name="select_rows" class="select_rows" data-tableid="dt_gal" /></th>
			<th>Image</th>
			<th>Name</th>
			<th>Size</th>
			<th>Date</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><input type="checkbox" name="row_sel" class="row_sel" /></td>
			<td style="width: 60px"><a href="gallery/Image10.jpg"
				title="Image 10" class="cbox_single thumbnail"> <img alt=""
					src="gallery/Image10_tn.jpg" style="height: 50px; width: 50px">
			</a>
			</td>
			<td>Lorem ipsum dolor sit<br /> <small>Image10.jpg</small>
			</td>
			<td>200 KB</td>
			<td>28/06/2012</td>
			<td><a href="#" class="sepV_a" title="Edit"><i class="icon-pencil"></i>
			</a> <a href="#" class="sepV_a" title="View"><i class="icon-eye-open"></i>
			</a> <a href="#" title="Delete"><i class="icon-trash"></i> </a>
			</td>
		</tr>
	</tbody>
</table>
</div>
</div>