<div class="row-fluid">
	<h1 class="heading">Gerenciar Estoque</h1>
	<div class="row-fluid">
		<button class="btn">Salvar</button>
	</div>	
	<div class="row-fluid">
		<table class="table table-striped table-bordered product-results" style="width:70%;" >
			<thead>
					<tr>
						<th>ID</th>
						<th>Imagem</th>
						<th class="span4">Nome</th>
						<th class="span2">SKU</th>
						<th class="span1" colspan="2">Estoque</th>											
					</tr>
			</thead>
			<tbody>
				<tr>
						
						<td></td>
						<td></td>
						<td><input type="text" name="search_name" value="" class="span12"/></td>
						<td><input type="text" name="search_sku" value="" class="span12"/></td>
						
						<td>
							<input type="text" name="search_stock_from" value="" class="span12" />
							<input type="text" name="search_stock_to" value="" class="span12" />
						</td>						
						<td><button class="btn search">Buscar</button></td>
					</tr>
				<?= $this->products;?>
			</tbody>
		</table>
	</div>
	<div class="row-fluid">
		<button class="btn">Salvar</button>
	</div>
</div>

<script type="text/javascript">
$('button.search').on('click',function(){

	 var name = $('input[name="search_name"]').val();
	 var sku = $('input[name="search_sku"]').val();
	 var stockFrom =  $('input[name="search_stock_from"]').val();
	 var stockTo =  $('input[name="search_stock_to"]').val();	 
	 
	 getProductTable(name,sku,1,stockFrom,stockTo,'','',false,true,false,false);
});
</script>