<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
    foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>


<form method="post" action="add" id="addCustomer">
    <h1 class="heading">Cadastrar Cliente</h1>
    <div class="row-fluid">
        <div class="span6">

            <h3 class="heading">Dados Gerais</h3>
            <div class="row-fluid">
                <div class="span6">
                
                    <label for="name">Nome: </label> 
                    <input class="span12" type="text" value="" name="name" />
                </div>
                <div class="span6">
                    <label for="lastname">Sobrenome: </label> <input class="span12"
                        type="text" value="" name="lastname" />
                </div>
            </div>
            <div class="row-fluid">
            <div class="span6">
            <label for="vat">CPF: </label> 
            <input class="span7" type="text" value="" name="vat" /> <label for="birth">Data de Nascimento: </label>
            <input class="span6" type="text" value="" name="birth" /> 
            </div>
            <div class="span6">
            <label for="gender">Sexo: </label> 
            <select class="span7" name="gender">
                <option value="0">Masculino</option>
                <option value="1">Feminino</option>
            </select>
            </div>
            </div>
        </div>
        <div class="span6">
            <h3 class="heading">Dados de Acesso</h3>
            <label for="email">Email: </label> 
            <input type="text" value="" class="span8" name="email" />
            <label for="password">Senha: </label>
            <input type="password" class="span4" value="" name="password" /> 
            <label for="confirm">Confirme a Senha: </label>
            <input type="password" class="span4" value="" name="confirm" />
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <h3 class="heading">Endereço</h3>

            <label for="address">Logradouro:</label> <input class="span6"
                type="text" name="address" /> <label for="numer">Número:</label> <input
                class="span1" type="text" name="number" /> <label for="complement">Complemento:</label>
            <input class="span2" type="text" name="complement" /> <label
                for="zip">CEP:</label> <input class="span2" type="text" name="zip" />
            <label for="city">Cidade:</label> <input class="span3" type="text"
                name="city" /> <label for="state">Estado:</label> <input
                class="span2" type="text" name="state" /> <label for="country">País:</label>
            <select class="span2" name="country">
                <option value="0">Escolha</option>
                <?php foreach ($this->countries as $country){?>
                <option value="<?php echo $country->getId(); ?>">
                    <?php echo $country->getName(); ?>
                </option>
                <?php } ?>
            </select> 
            <button type="submit" class="btn btn-gebo">Salvar</button>
        </div>
    </div>
</form>

<script type="text/javascript">

$(document).ready(function(){

    $('[name=birth]').mask('00/00/0000');
    $('[name=vat]').mask('000.000.000-00');
    
})
    
</script>
