<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
    foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>


<form method="post" action="/admin238/customer/edit/id/<?php echo $this->entity->getClient()->getId();?>" id="addCustomer">
    <h1 class="heading">Editar Cliente</h1>
    <div class="row-fluid">
        <div class="span6">

            <h3 class="heading">Dados Gerais</h3>
            <div class="row-fluid">
                <div class="span6">                
                    <label for="name">Nome: </label> 
                    <input class="span12" type="text" value="<?php echo $this->entity->getClient()->getFirstName();?>" name="name" required />
                </div>
                <div class="span6">
                	<label for="lastname">Sobrenome: </label> 
                	<input class="span12" type="text" value="<?php echo $this->entity->getClient()->getLastName();?>" name="lastname" required/>
                </div>
            </div>
            <div class="row-fluid">
            <div class="span6">
            <label for="vat">CPF: </label> 
            <input class="span7" type="text" value="<?php echo $this->entity->getClient()->getCpf();?>" name="cpf" required/> 
            <label for="birth">Data de Nascimento: </label>
            <input class="span6" type="text" value="<?php echo $this->entity->getClient()->getDateBirth()->format('d-m-Y');?>" name="birth" required/> 
            </div>
            <div class="span6">
            <label for="gender">Sexo: </label> 
            <select class="span7" name="gender" required>
                <option value="0"<?php if($this->entity->getClient()->getGender() == 0){echo 'selected';};?>>Masculino</option>
                <option value="1"<?php if($this->entity->getClient()->getGender() != 0){echo 'selected';};?>>Feminino</option>
            </select>
            </div>
            </div>
        </div>
        <div class="span6">
            <h3 class="heading">Dados de Acesso</h3>
            <label for="email">Email: </label> 
            <input type="text" value="<?php echo $this->entity->getClient()->getEmail();?>" class="span8" name="email" required/>
            <label for="password">Nova Senha: </label>
            <input type="password" class="span4" value="" name="password" /> 
            
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <h3 class="heading">Endereços</h3>
			<div class="tabbable tabbable-bordered">
				<ul class="nav nav-tabs">
					<li class="active"><a data-toggle="tab" href="#tab_br1">Cobrança</a>
					</li>
					<li class=""><a data-toggle="tab" href="#tab_br2">Entrega</a></li>
					
				</ul>
				<div class="tab-content">
					<div id="tab_br1" class="tab-pane active">
						<h4 class="heading">Endereço de Cobrança</h4>
						
						<label>Logradouro:</label> 
							<input class="span6" type="text" name="billing-address" value="<?php if(isset($this->addresses['billing-street'])){echo $this->addresses['billing-street'];};?>"/> 
						<label>Número:</label>
							<input class="span1" type="text" name="billing-number" value="<?php if(isset($this->addresses['billing-number'])){echo $this->addresses['billing-number'];};?>"/> 
						<label>Complemento:</label> 
							<input class="span2" type="text" name="billing-complement" value="<?php if(isset($this->addresses['billing-complement'])){echo $this->addresses['billing-complement'];};?>"/> 
						<label>CEP:</label> 
						<input class="span2" type="text" name="billing-zip" value="<?php if(isset($this->addresses['billing-zip'])){echo $this->addresses['billing-zip'];};?>"/>
						<label>País:</label> 
							<select class="span2" name="billing-country">
								<option value="0">Escolha</option>
								<?php foreach ($this->countries as $country){?>								
								<option value="<?php echo $country->getId(); ?>" <?php if(isset($this->addresses['billing-country']) && $country->getId() == $this->addresses['billing-country']){echo 'selected';};?>>
									<?php echo $country->getName(); ?>
								</option>
								<?php } ?>
							</select>
						<label>Estado:</label>
							<select class="span2" type="text" name="billing-state">
								<option value="<?php echo $this->addresses['billing-state'];?>"><?php echo $this->addresses['billing-state-name'];?></option>
							</select>
							 
						<label>Cidade:</label>
							<input class="span3" type="text" name="billing-city" value="<?php echo $this->addresses['billing-city']?>"/> 
						
					</div>
					<div id="tab_br2" class="tab-pane">
						<h4 class="heading">Endereço de Entrega</h4>
						<label class="checkbox"><input type="checkbox" name="same-address"/>Mesmo endereço de cobrança</label>						
						<label for="address">Logradouro:</label> 
							<input class="span6" type="text" name="shipping-address" value="<?php if(isset($this->addresses['shipping-street'])){echo $this->addresses['shipping-street'];};?>"/> 
						<label for="numer">Número:</label>
							<input class="span1" type="text" name="shipping-number" value="<?php if(isset($this->addresses['shipping-number'])){echo $this->addresses['shipping-number'];};?>"/> 
						<label for="complement">Complemento:</label> 
							<input class="span2" type="text" name="shipping-complement" value="<?php if(isset($this->addresses['shipping-complement'])){echo $this->addresses['shipping-complement'];};?>"/> 
						<label for="zip">CEP:</label> 
							<input class="span2" type="text" name="shipping-zip" value="<?php if(isset($this->addresses['shipping-zip'])){echo $this->addresses['shipping-zip'];};?>"/> 
						<label for="country">País:</label> 
							<select class="span2" name="shipping-country" >
								<option value="0">Escolha</option>
								<?php foreach ($this->countries as $country){?>
								<option value="<?php echo $country->getId(); ?>" <?php if(isset($this->addresses['shipping-country']) && $country->getId() == $this->addresses['shipping-country']){echo 'selected';};?>>
									<?php echo $country->getName(); ?>
								</option>
								<?php } ?>
							</select>
						<label>Estado:</label>
							<select class="span2" type="text" name="shipping-state">
							<?php if (isset($this->addresses['shipping-state'])){?>
								<option value="<?php echo $this->addresses['shipping-state'];?>"><?php echo $this->addresses['shipping-state-name'];?></option>
							<?php }?>
							</select> 
						<label for="city">Cidade:</label>
							<input class="span3" type="text" name="shipping-city" value="<?php if(isset($this->addresses['shipping-city'])){echo $this->addresses['shipping-city'];};?>"/> 
					</div>					
				</div>
				<button onclick="formSend()" class="btn btn-gebo">Salvar</button>
			</div>

		</div>
    </div>
</form>

<script type="text/javascript">

$(document).ready(function(){

    $('[name=birth]').mask('00/00/0000');
    $('[name=cpf]').mask('000.000.000-00');

	// Preenche o endereço de entrega de acordo com o de cobrança
    
    $('[name=same-address]').click(function(){
        $('input[name=shipping-address]').val($('input[name=billing-address]').val());
        $('input[name=shipping-number]').val($('input[name=billing-number]').val());
        $('input[name=shipping-complement]').val($('input[name=billing-complement]').val());
        $('input[name=shipping-zip]').val($('input[name=billing-zip]').val());
        $('input[name=shipping-city]').val($('input[name=billing-city]').val());
        var country = $('select[name=billing-country] option:selected').html().trim();
        $("select[name=shipping-country] option").each(function() { this.selected = (this.text == country); });
        var state = $('select[name=billing-state] option:selected').html().trim();
        $("select[name=shipping-state] option").each(function() { this.selected = (this.text == state); });

    });
	
    $('[name=billing-country]').change(function(){ 
        $.get("/admin238/customer/call-states",{country:$('[name=billing-country]').val()},function(data){
        	$("select[name=billing-state]").html(data);
        	$("select[name=billing-state]").prop('disabled',false);
        	$("select[name=shipping-state]").html(data);
        	$("select[name=shipping-state]").prop('disabled',false);        	
        });
    });

    $('[name=billing-state]').change(function(){        
        	$("input[name=billing-city]").prop('disabled',false);
        	$("input[name=shipping-city]").prop('disabled',false);
    });
    

    $('[name=shipping-country]').change(function(){ 
        $.get("/admin238/customer/call-states",{country:$('[name=shipping-country]').val()},function(data){
        	$("select[name=shipping-state]").html(data);
        	$("select[name=shipping-state]").prop('disabled',false);
        });
    }); 

    $('[name=shipping-state]').change(function(){        
    	$("input[name=shipping-city]").prop('disabled',false);
    });

   
});

	jQuery.validator.addMethod("notEqual", function(value, element, param) {
		return this.optional(element) || value != param;
	}, "Campo obrigatório");	

 function formSend(){
	
   $('#addCustomer').validate({
		rules:{
			name:{
				required:true
			},
			email:{
				required:true,
				email:true
			}
		},
		messages:{
            name:{
                required: "O campo nome é obrigatorio."               
            },
            email:{
                required: "O campo email é obrigatório.",
                email: 'Digite um email válido'               
            }			
		}
    });

   
   
 }
    
</script>
