<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
    foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>


<form method="post" action="/admin238/customer/edit/id/<?php echo $this->entity->getId();?>" id="addCustomer">
    <h1 class="heading">Editar Cliente</h1>
    <div class="row-fluid">
        <div class="span6">

            <h3 class="heading">Dados Gerais</h3>
            <div class="row-fluid">
                <div class="span6">                
                    <label for="name">Nome: </label> 
                    <input class="span12" type="text" value="<?php echo $this->entity->getFirstName();?>" name="name" required />
                </div>
                <div class="span6">
                	<label for="lastname">Sobrenome: </label> 
                	<input class="span12" type="text" value="<?php echo $this->entity->getLastName();?>" name="lastname" required/>
                </div>
            </div>
            <div class="row-fluid">
            <div class="span6">
            <label for="vat">CPF: </label> 
            <input class="span7" type="text" value="<?php echo $this->entity->getCpf();?>" name="cpf" required/> 
            <label for="birth">Data de Nascimento: </label>
            <input class="span6 date" type="text" value="<?php echo $this->entity->getDateBirth()->format('d-m-Y');?>" name="birth" required/> 
            </div>
            <div class="span6">
            <label for="gender">Sexo: </label> 
            <select class="span7" name="gender" required>
                <option value="0"<?php if($this->entity->getGender() == 0){echo 'selected';};?>>Masculino</option>
                <option value="1"<?php if($this->entity->getGender() != 0){echo 'selected';};?>>Feminino</option>
            </select>
            </div>
            </div>
        </div>
        <div class="span6">
            <h3 class="heading">Dados de Acesso</h3>
            <label for="email">Email: </label> 
            <input type="text" value="<?php echo $this->entity->getEmail();?>" class="span8" name="email" required/>
            <label for="password">Nova Senha: </label>
            <input type="password" class="span4" value="" name="password" /> 
            
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <h3 class="heading">Endereços</h3>
			<div class="tabbable tabbable-bordered">
				<ul class="nav nav-tabs">
					<li class="active"><a data-toggle="tab" href="#tab_br1">Cobrança</a>
					</li>
					<li class=""><a data-toggle="tab" href="#tab_br2">Entrega</a></li>
					
				</ul>
				<div class="tab-content">
					<div id="tab_br1" class="tab-pane active">
						<h4 class="heading">Endereço de Cobrança</h4>
						
						<label>Logradouro:</label> 
							<input class="span6" type="text" name="billingaddress" value="<?php if($this->billing){if($this->billing->getStreet() !== null){echo $this->billing->getStreet();};}?>"/> 
						<label>Número:</label>
							<input class="span1" type="text" name="billingnumber" value="<?php if($this->billing){if($this->billing->getNumber() !== null){echo $this->billing->getNumber();};}?>"/> 
						<label>Complemento:</label> 
							<input class="span2" type="text" name="billingcomplement" value="<?php if($this->billing){if($this->billing->getComplement() !== null){echo $this->billing->getComplement();};}?>"/> 
						<label>CEP:</label> 
						<input class="span2" type="text" name="billingzip" value="<?php if($this->billing){if($this->billing->getZip() !== null){echo $this->billing->getZip();};}?>"/>
						<label>País:</label> 
							<select class="span2" name="billingcountry">
								<option value="0">Escolha</option>
								<?php foreach ($this->countries as $country){?>								
								<option value="<?= $country->getId(); ?>" <?php if($this->billing){if($this->billing->getCountry()->getId() !== null && $country->getId() == $this->billing->getCountry()->getId()){echo 'selected';};}?>>
									<?= $country->getName(); ?>
								</option>
								<?php } ?>
							</select>
						<label>Estado:</label>
							<select class="span2" type="text" name="billingstate">
							    <?php if($this->billing){if($this->billing->getState() !== null){?>
								<option value="<?= $this->billing->getState()->getId();?>"><?= $this->billing->getState()->getName();?></option>
							    <?php }}?>
							</select>
							 
						<label>Cidade:</label>
							<input class="span3" type="text" name="billingcity" value="<?php if($this->billing){echo $this->billing->getCity();}?>"/> 
						
					</div>
					<div id="tab_br2" class="tab-pane">
						<h4 class="heading">Endereço de Entrega</h4>
						<label class="checkbox"><input type="checkbox" name="same-address"/>Mesmo endereço de cobrança</label>						
						<label for="address">Logradouro:</label> 
							<input class="span6" type="text" name="shippingaddress" value="<?php if($this->shipping){if($this->shipping->getStreet() !== null){echo $this->shipping->getStreet();};}?>"/> 
						<label for="numer">Número:</label>
							<input class="span1" type="text" name="shippingnumber" value="<?php if($this->shipping){if($this->shipping->getNumber() !== null){echo $this->shipping->getNumber();};}?>"/> 
						<label for="complement">Complemento:</label> 
							<input class="span2" type="text" name="shippingcomplement" value="<?php if($this->shipping){if($this->shipping->getComplement() !== null){echo $this->shipping->getComplement();};}?>"/> 
						<label for="zip">CEP:</label> 
							<input class="span2" type="text" name="shippingzip" value="<?php if($this->shipping){if($this->shipping->getZip() !== null){echo $this->shipping->getZip();};}?>"/> 
						<label for="country">País:</label> 
							<select class="span2" name="shippingcountry" >
								<option value="0">Escolha</option>
								<?php foreach ($this->countries as $country){?>
								<option value="<?= $country->getId(); ?>" <?php if($this->shipping){if($this->shipping->getCountry()->getId() !== null && $country->getId() == $this->shipping->getCountry()->getId()){echo 'selected';};}?>>
                                    <?= $country->getName(); ?>
                                </option>
								<?php } ?>
							</select>
						<label>Estado:</label>
							<select class="span2" type="text" name="shippingstate">
							<?php if($this->shipping){if ($this->shipping->getState() !== null){?>
								<option value="<?= $this->shipping->getState()->getId();?>"><?= $this->shipping->getState()->getName();?></option>
							<?php }}?>
							</select> 
						<label for="city">Cidade:</label>
							<input class="span3" type="text" name="shippingcity" value="<?php if($this->shipping){if($this->shipping->getCity() !== null){echo $this->shipping->getCity();};}?>"/> 
					</div>					
				</div>
				<button onclick="formSend()" class="btn btn-gebo">Salvar</button>
			</div>

		</div>
    </div>
</form>

<script type="text/javascript">

$(document).ready(function(){

    $('[name=birth]').mask('00/00/0000');
    $('[name=cpf]').mask('000.000.000-00');

	// Preenche o endereço de entrega de acordo com o de cobrança
    
    $('[name=same-address]').click(function(){
        $('input[name=shippingaddress]').val($('input[name=billingaddress]').val());
        $('input[name=shippingnumber]').val($('input[name=billingnumber]').val());
        $('input[name=shippingcomplement]').val($('input[name=billingcomplement]').val());
        $('input[name=shippingzip]').val($('input[name=billingzip]').val());
        $('input[name=shippingcity]').val($('input[name=billingcity]').val());
        var country = $('select[name=billingcountry] option:selected').html().trim();
        $("select[name=shippingcountry] option").each(function() { this.selected = (this.text == country); });
        var state = $('select[name=billingstate] option:selected').html().trim();
        $("select[name=shippingstate] option").each(function() { this.selected = (this.text == state); });

    });
	
    $('[name=billingcountry]').change(function(){ 
        $.get("/admin238/customer/call-states",{country:$('[name=billingcountry]').val()},function(data){
        	$("select[name=billingstate]").html(data);
        	$("select[name=billingstate]").prop('disabled',false);
        	$("select[name=shippingstate]").html(data);
        	$("select[name=shippingstate]").prop('disabled',false);        	
        });
    });

    $('[name=billingstate]').change(function(){        
        	$("input[name=billingcity]").prop('disabled',false);
        	$("input[name=shippingcity]").prop('disabled',false);
    });
    

    $('[name=shippingcountry]').change(function(){ 
        $.get("/admin238/customer/call-states",{country:$('[name=shippingcountry]').val()},function(data){
        	$("select[name=shippingstate]").html(data);
        	$("select[name=shippingstate]").prop('disabled',false);
        });
    }); 

    $('[name=shippingstate]').change(function(){        
    	$("input[name=shippingcity]").prop('disabled',false);
    });

   
});

	jQuery.validator.addMethod("notEqual", function(value, element, param) {
		return this.optional(element) || value != param;
	}, "Campo obrigatório");	

 function formSend(){
	
   $('#addCustomer').validate({
		rules:{
			name:{
				required:true
			},
			email:{
				required:true,
				email:true
			}
		},
		messages:{
            name:{
                required: "O campo nome é obrigatorio."               
            },
            email:{
                required: "O campo email é obrigatório.",
                email: 'Digite um email válido'               
            }			
		}
    });

   
   
 }
    
</script>
