<?php 

if (isset($this->msgSuccess)){
   
    foreach ($this->msgSuccess as $message){?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<?php 

if (isset($this->msgError)){
   
    foreach ($this->msgError as $message){?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message; ?>
        </div>
         
<?php }
    
}?>

<div class="row-fluid">
    <div class="span12">
        <h1 class="heading">Clientes<a href='/admin/customer/add' class='btn btn-add'>Adicionar</a></h1>
        <div class="row-fluid paginator">
        <?php echo $this->pagination;?>
        </div>
        <table class="table table-bordered table-striped table_vam customerResults" >
            <thead>
                <tr>
                    <th></th>
                    <th><input type="text" class="span12" name="searchName" placeholder="Nome..."/></th>
                    <th><input type="text" class="span12" name="searchEmail" placeholder="Email..."/></th>
                    <th><input type="text" class="span12" name="searchState" placeholder="Estado..."/></th>
                    <th><input type="text" class="span12" name="searchCountry" placeholder="País..."/></th>
                    <th><input name="searchSince" type="text" class="span12 date" placeholder="Desde..."/></th>
                    <th><input name="searchLastLogin" type="text" class="span12 date" placeholder="Ultimo Login..."/></th>
                    <th>
                    	<select name="searchStatus" class="span12">
                    		<option value="1" selected>Ativo</option>
                    		<option value="0">Inativo</option>
                    	</select>
                    </th>
                    <th><button class="btn btn-gebo" id="searchCustomer">Buscar</button></th>
                </tr>            
                <tr>
                    <th class="table_checkbox"><input type="checkbox"
                        name="select_rows" class="select_rows" data-tableid="dt_gal" /></th>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Estado</th>
                    <th>País</th>
                    <th>Desde</th>
                    <th>Ultimo Login</th>
                    <th>Status</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
            	<?php foreach($this->clients as $client){ 
            	   $address = $client->getAddress();    
            	?>
            	<tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td><?php echo $client->getFirstName() . ' ' . $client->getLastName();?></td>
                    <td><?php echo $client->getEmail();?></td>
                    <td><?php echo $address[0]->getState()->getName();?></td>
                    <td><?php echo $address[0]->getCountry()->getName();?></td>
                    <td><?php echo $client->getDateCreate()->format('d/m/Y');?></td>
                    <td><?php if ($client->getLastLogin()){echo $client->getLastLogin()->format('d/m/Y');};?></td>
                    <td><?php if ($client->getStatus() == 0){echo 'Inativo';}else{echo 'Ativo';};?></td>
                    <td>
                        <a href="/admin238/customer/edit/id/<?php echo $client->getId();?>" class="sepV_a" title="Editar"><i class="icon-pencil"></i></a>
                        <?php if ($client->getStatus() != 0){?>
                        <a href="/admin238/customer/disable/id/<?php echo $client->getId()?>" title="Desativar">                        
                            <i class="splashy-gem_remove"></i>                          
                        </a>
                        <?php }?>
                        <?php if ($client->getStatus() == 0){?>           
                        <a href="/admin238/customer/enable/id/<?php echo $client->getId()?>" title="Ativar">
                            <i class="splashy-okay"></i>                           
                        </a>
                        <?php }?>
                    </td>
                </tr>  
            	<?php }?>                
            </tbody>
        </table>
                
        <div class="row-fluid paginator">
        <?php echo $this->pagination;?>
        </div>
    </div>
</div>